### ISSUE TITLE
Clock not starting

### ISSUE THREAD

**Issue by martinchristov** [objectivehtml/FlipClock#104]
Hi there.
For some reason I cannot get the clock to start ticking.
I've tried various options from your examples, but nothing makes it start.
Calling the .start() method responds with: "Trying to start timer when countdown already at 0 "

**Comment by gersonj13** [comment]
I have the same problem now!

**Comment by Nsuidara** [comment]
Display: Minutes:Seconds 00:01 
when i try start "Trying to start timer when countdown already at 0"

how i can check it ?
