### ISSUE TITLE
Bold text is blinking in Safari when using FlipClock.js

### ISSUE THREAD

**Issue by nunull** [objectivehtml/FlipClock#12]
In Safari, bold text-elements (styled with CSS), which are not part of the FlipClock, are blinking (getting bolder and thinner again) every second when using FlipClock.js.

Maybe it is an Safari-issue, but i think it should be a know-issue anyway.

System: OSX 10.8, Safari 6.0.2

**Comment by backciro** [comment]
tannerhodges u save my life
