### ISSUE TITLE
Changing size?

### ISSUE THREAD

**Issue by lggwettmann** [objectivehtml/FlipClock#13]
I really like your plugin - thanks for the work. Also the ease animation would look great to be implemented.

I wondered how I can easily change the size of the counter without changing all 1000 css defaults. 

Thanks in advance

**Comment by Jawaad** [comment]
Hi

I know its nearly a year old, but here is the manual solution (its really not '1000 css defaults'):

.flip-clock-wrapper ul {width: 40px;height: 78px;margin: 0 2px;}
.flip-clock-wrapper ul li {line-height: 78px;}
.flip-clock-wrapper ul li a div div.inn {border-radius: 3px;font-size: 50px;}
.flip-clock-wrapper ul li a div.down {border-bottom-left-radius: 3px; border-bottom-right-radius: 3px;}
.flip-clock-wrapper ul li a div.up:after {top: 38px;height: 2px;}

the '.flip-clock-wrapper ul' properties represent each digit's containing box.

the line-height of '.flip-clock-wrapper ul li' should match the height of '.flip-clock-wrapper ul'.

the actual number inside the box is represented by '.flip-clock-wrapper ul li a div div.inn' so I have adjusted the font size here.

ive reduced the border radius' of '.flip-clock-wrapper ul li a div div.inn' and '.flip-clock-wrapper ul li a div.down' for aesthetics. 

'.flip-clock-wrapper ul li a div.up:after' represents the line between the top and bottom parts of the flip. Its 'top' property has to be the height of '.flip-clock-wrapper ul' divided by 2 minus its own height divided by 2 [(78/2) - (2/2) = 38].

hope this helps

**Comment by iammart** [comment]
@Jawaad Thanks for explaining this it helped :)

**Comment by Hillelman** [comment]
@Jawaad You are the best, thank you!
I even shrink it more and added a few more line to adjust the positions of the dots:

/* Adjust the position of the top's dot */
.flip-clock-dot.top {
  top: 10px;
}
/* Adjust the position of the bottom's dot */
.flip-clock-dot.bottom {
  bottom: 0;
  top: 25px;
}
/* Adjust the size of both dots */
.flip-clock-dot{
  width: 7px;
  height: 7px;
}
/* Adjust the space between the wrappers */
.flip-clock-divider {
  width: 17px;
  height: 45px;
}

**Comment by j0hj0h** [comment]
Thanks @Jawaad and @Hillelman! I put it together into a less source, that allows sizing by parameters:
http://jsfiddle.net/fd3600yv/

**Comment by jeepnet** [comment]
Thanks @j0hj0h ! I added it to my project, and it worked like a charm.

**Comment by j0hj0h** [comment]
Glad to hear that @jeepnet

**Comment by ianpurvis** [comment]
Thanks for this!!!

**Comment by madahmani** [comment]
And another thank you for this.

**Comment by brianespinosa** [comment]
Hi All,

Just to keep the discussion clean I am locking this. The project has moved past this solution already. And an even better solution will be available in v1.

Thanks for the support!
