### ISSUE TITLE
Unnecessary animation from 91 to 01 at the beginning of count

### ISSUE THREAD

**Issue by vickyRuiz** [objectivehtml/FlipClock#137]
Hi! First of all, I love this script, it is a really cool way of displaying time and counting things!

I am currently using as a counter, to go from 00 to 04 or some other small number. I want it to have 2 digits always. The problem is that the first digit is always animated as coming from 9. And as the first digit animation is slower than the second, it looks like it counts 91, 92, 03, 04. I've been looking at the code, but the JS is a bit advanced for me, could you help?

**Comment by meinhardmeintjes** [comment]
It's been a year and this still hasn't been fixed?? Im experiencing the same issue... Also if I want to start at, say, 14, it just starts at 13. When I change it to 15, it starts at 15?? 

A fix would be dearly appreciated!!

**Comment by nmeynard** [comment]
With last version it is the same problem...
So sad it has been abandonned

**Comment by objectivehtml** [comment]
Library went on hiatus for a while. But new v1 release candidate with tons of improvements is on the js-es6 branch. Will be the v1 release shortly. Library has been completely rewritten. This should be addressed in the newest version.
