### ISSUE TITLE
console log?

### ISSUE THREAD

**Issue by ghost** [objectivehtml/FlipClock#138]
Hi,

just wondering why there's a console.log(str) on line 536 in compiled/flipclock.js?

I removed it but is it necessary?

**Comment by jm3** [comment]
Oops, this guy is back at [line 333 of libs/time.js](https://github.com/objectivehtml/FlipClock/blob/17d9f3f1dd0da4918b3ff5dad4b03d737f9fb744/src/flipclock/js/libs/time.js#L333)! 🕐
