### ISSUE TITLE
Issue with numbers rendering

### ISSUE THREAD

**Issue by johngray** [objectivehtml/FlipClock#147]
Hello. I wanted to try FlipClock and immediately stumbled upon the issue with number rendering. Everything else is running smooth. On my site I am using Bootstrap 2.3.2.
Browser: Chrome 38.0.2125.66 beta-m
![bug](https://cloud.githubusercontent.com/assets/1721438/4496481/bfbf39b6-4a65-11e4-9a19-3d53685652c6.jpg)

**Comment by brianespinosa** [comment]
I am going to mark this as closed. Cannot duplicate this issue... and from what I am seeing, it appears that the screenshot, original post was using the SCSS that existed in the project... which was actually a few versions behind the actual CSS FlipClock is currently using. Without a working link there is no way to troubleshoot this. There are other issues going on as well, such as the alignment of the colon separators.
