### ISSUE TITLE
Countdown always restart!

### ISSUE THREAD

**Issue by caroy** [objectivehtml/FlipClock#151]
How can i make the clock continue to countdown, so that it doesn't start from the beginning every time the page is loaded?

Is it a server problem?

Thanks

**Comment by kylejcorrigan** [comment]
@caroy if you use PHP you could also handle the date issue server side. This way the countdown will always start at the right time from your end date.  This means that if you have a coundown to a specific date it's as easy as this.  In my example I'm counting down to February 25th 2015.

```php
<?
$now = date('Y-m-d H:i:s');
$timefirst = strtotime($now);
$timesecond = strtotime('2015-02-25 00:00:00');
$difference = $timesecond - $timefirst;
?>
```
Then when you are initiating the countdown JS it's as easy as

```javasacript
<script type="text/javascript">
    var clock = $('.clock').FlipClock(<?=$difference?> ,{
	clockFace: 'DailyCounter',
	countdown: true
});
</script>

**Comment by coreyleedesigns** [comment]
@kylejcorrigan just wondering if I want to achieve a similar counter but instead of clock, it will be a simple counter with increasing numbers for ie. every 10 seconds. I will need it to not start from the initial number when page is loaded every time as well. 

Will I need to save that value to somewhere in a database?

Thanks.

**Comment by kylejcorrigan** [comment]
In a situation like that one, i probably would just use php to read(a file with a single line with the counter number) and write(over the value on the single line) every 10-20 seconds.  May be a little bit taxing on your server, but it's either that, or doing the same exact thing with a database(where you are writing every 10-20 seconds to the DB).

If you have multiple users hitting the page at once though... all bets off.

**Comment by objectivehtml** [comment]
This is precisely why I don't support this inherently in the library. There are so many ways one can store and recall the data, either in a file, cookie, localstorage, or a database, not even considering what language to use server-side.

I think the key is exactly what @kylejcorrigan mentioned about multiple users viewing the page at once. This will most definitely have a negative effect on your count.
