### ISSUE TITLE
href issue

### ISSUE THREAD

**Issue by KyleMcNutt** [objectivehtml/FlipClock#152]
In flipclock.js, there are two places where you wrap something in `<a href="#">`, the two example are bellow:

    createListItem: function(css, value) {
			return [
				'<li class="'+(css ? css : '')+'">',
					'<a href="#">',
						'<div class="up">',
							'<div class="shadow"></div>',
							'<div class="inn">'+(value ? value : '')+'</div>',
						'</div>',
						'<div class="down">',
							'<div class="shadow"></div>',
							'<div class="inn">'+(value ? value : '')+'</div>',
						'</div>',
					'</a>',
				'</li>'
			].join('');
		},

and 

    build: function() {
			var t = this;

			var time = this.factory.time.getTime(false, this.showSeconds);

			this.base(time);			
			this.meridiumText = this.getMeridium();			
			this.meridium = $([
				'<ul class="flip-clock-meridium">',
					'<li>',
						'<a href="#">'+this.meridiumText+'</a>',
					'</li>',
				'</ul>'
			].join(''));
						
			this.meridium.insertAfter(this.lists[this.lists.length-1].$el);
		},

Is there any specific reason for this? I only ask because in my project when you click on individual numbers in the clock or countdown it's causing an unwanted movement to the top of the page. This problem is fixed when I change the above code to `<a>`. Any comment would be appreciated.

**Comment by brianespinosa** [comment]
I am going to close this issue out in reference to #161 since any markup issues like this are getting fixed in v1.0. Technically this does not cause any issues with how FlipClock works and there are CSS overrides in the current version for the cursor to not show as a link pointer.
