### ISSUE TITLE
Countdown displays incorrectly when timer is reset using setTime(val) and duration exceeding 100 days

### ISSUE THREAD

**Issue by sergproua** [objectivehtml/FlipClock#153]
I was able to reproduce the issue by modifying the following in samples:
countdown-from-new-years.html 

as of 11/3/2014 it shows 306 days since new years. (306:MM:HH:SS)

if you try to reset and call
clock = $('.clock').FlipClock(0, {clockFace: 'DailyCounter'});
clock.setTime(diff);

it shows correct duration however formatting is skewed.
30:6MM:HH:SS

**Comment by objectivehtml** [comment]
This should be fixed in the dev branch. Note, this branch is breaking to the API. `clock.setTime` is now `clock.setFaceValue` and `clock.setCountdown()

**Comment by ykmutawa** [comment]
INSERT THIS SCRIPT
	        $('.clock.flip-clock-wrapper>span:eq(1)').insertAfter($('.clock.flip-clock-wrapper>ul:eq(2)'));
	        $('.clock.flip-clock-wrapper>span:eq(2)').insertAfter($('.clock.flip-clock-wrapper>ul:eq(4)'));
	        $('.clock.flip-clock-wrapper>span:eq(3)').insertAfter($('.clock.flip-clock-wrapper>ul:eq(6)'));
