### ISSUE TITLE
Changing tabs causes timer to run slower

### ISSUE THREAD

**Issue by GarrethDottin** [objectivehtml/FlipClock#155]
For some reason when I change tabs the timer starts running slower.I compared it against google's timer and when I remain on the same page it runs fine but when changing tabs it becomes increasingly slower.  I instantiate it with the following code. 

flipClockApi.createClock = function () {
        var Clock = $('.your-clock').FlipClock({
            autoStart: false,
            countdown: true,
            clockFace: "MinuteCounter",
        });
        return Clock;
    };

```
    flipClockApi.clock = flipClockApi.createClock();
```

   flipClockApi.startClock = function(scope) {
            flipClockApi.clock.start();
    };

**Comment by robert2d** [comment]
Suggest using `$(window).on("focus", function(event) { some form of reset });`

**Comment by objectivehtml** [comment]
Why would you suggest that over that has been posted?

**Comment by robert2d** [comment]
Cross browser compatible and simpler

--
Dave Robertson
Chief Technology Officer
CricHQ
E: david.robertson@crichq.com
Ph: +64 (0)29 770 9595

On 9/01/2015, at 8:41 am, Justin Kimbrell <notifications@github.com> wrote:

Why would you suggest that over that has been posted?

—
Reply to this email directly or view it on GitHub
<https://github.com/objectivehtml/FlipClock/issues/155#issuecomment-69236278>
.

**Comment by robert2d** [comment]
I have implemented the "focus" solution with success already, but we just destroy and then recreate the whole thing. Not the best way to do this obviously but I haven't looked at the internals of FlipClock to see about a reset yet. if you pointe me in the right direction for a reset I'll put together a pull request and you can at least use it for investigation. However I do like the already recommended solution but just wondering wether its a bit more than is required to solve this issue..

**Comment by objectivehtml** [comment]
`clock.reset()` will reset the clock back to the original value. But after looking at this solution, I don't think the code you posted can be used in FlipClock. What needs to happen is when the user minimizes the window or changes tabs, the clock still keeps accurate time in the background. And once the user returns to the window or tab, the clock is updated with the correct value. I don't know any other way to do this other than using a Web Worker. I also think only support IE10+ is fine for this feature. Users with older IE browsers will still have a working clock, as long as they don't minimize the window or switch tabs.

**Comment by mateuszpalyz** [comment]
@objectivehtml any progress with this issue, reseting countdown clock is not an option ;)

**Comment by objectivehtml** [comment]
Very long time coming, but this library has been rewritten to use requestAnimatioFrame's so no longer using intervals. Works much better now in inactive tabs. This also fixed the issue where the clock could fall behind the actual time. Check out the new v1 drag on the new js-es6 branch and open a new issue if it' still an issue. Closing this old thread.
