### ISSUE TITLE
Setting a timezone with the clock

### ISSUE THREAD

**Issue by scaryguy** [objectivehtml/FlipClock#166]
Hi,

I'd like to use your library to show a different timezone than client's. The clock should always show GMT+02:00 for all users browsing that page whichever timezone they're in.  I tried this to get GMT+02:00 (I'm at GMT-08:00):

``` js
clock = $('.clock').FlipClock(((3600*10)), {
        clockFace: 'TwentyFourHourClock'
    });
```

It looks like it works but after a while, minutes goes forward. I think seconds count faster than they're supposed to do. It's really weired. Let's say at the first moment it shows "00:01:00" and after a 1 minute (measured by another clock) it shows "00:02:10".

Any ideas?

**Comment by objectivehtml** [comment]
Hm... Yeah this is really strange. I am not sure about this. I will have a take a closer look once I get a chance. I just use the native JS interval methods, so it should work based off the system clock.

**Comment by objectivehtml** [comment]
new v1 draft release has been rewritten to address stuff like this. You can now pass a native date object to the library, and set the timezone however you normally would. new version of library makes no assumption of clock value or time zone.
