### ISSUE TITLE
how to proceed Resizing

### ISSUE THREAD

**Issue by Xsmael** [objectivehtml/FlipClock#170]
Hi, is it posssible to make it responsive ? so that the size will grow/decrease according to screen size?

**Comment by objectivehtml** [comment]
We are in the process of rewriting many components of the library. You can find the details here.

https://github.com/objectivehtml/FlipClock/issues/161

**Comment by Xsmael** [comment]
Okay thanks!

2015-01-06 6:24 GMT+05:30 Justin Kimbrell <notifications@github.com>:
