### ISSUE TITLE
Align to center

### ISSUE THREAD

**Issue by RockyTV** [objectivehtml/FlipClock#172]
Is there a way to align the clock to the center of the page? I tried, but it didn't work...

**Comment by brianespinosa** [comment]
There are a number of ways to do this. Can you post an example of your code?

**Comment by RockyTV** [comment]
````
<link rel="stylesheet" href="{{ site.baseurl }}/assets/flipclock.css">
<script type="text/javascript" src="{{ site.baseurl }}/assets/jquery.min.js"></script>
<script type="text/javascript" src="{{ site.baseurl }}/assets/flipclock.min.js"></script>

<script type="text/javascript">
	var clock;
	
	$(document).ready(function (){
		var h1z1Date = Date.UTC(2015, 00, 15, 18);
		var currentDate = new Date();
		
		var diff = (h1z1Date / 1000) - (currentDate.getTime() / 1000);
		
		clock = $('.h1z1-clock').FlipClock(diff, {
			clockFace: 'DailyCounter',
			autoStart: true,
			countdown: true,
			callbacks: {
				stop: function() {
					$('.steam-store').html('<iframe src="http://store.steampowered.com/widget/295110/" frameborder="0" width="646" height="190"></iframe>')
				}
			}
		});
	});
</script>


<div align="center">
	<div class="h1z1-clock"></div>
</div>
<div class="steam-store" align="center">
	<p style="text-size: 18px;">until H1Z1's Early Access release on Steam</p>
</div>

<div class="separator"></div>
````

**Comment by brianespinosa** [comment]
align="center" on a div is not how you should be doing it. And in the future you should shy away from using attributes to style your page. This sort of styling should be done in CSS.

I'm not in front of the computer right now, but if you give the flipclock parent container a style of text-align: center, that should do it. You may have to give the flipclock container an inline-block display style, too.

In the future, posting a working code example on your server or on a service like codepen is a much better way to show the issue you're experiencing. Someone can edit your post and show you the solution that way a lot easier, too.=

**Comment by KyleMcNutt** [comment]
This is _by no means_ the best solution but I was able to get it to center using the code in this CodePen:

http://codepen.io/anon/pen/dPvbZP

For some reason using `text-align: center` as @brianespinosa suggested above didn't work, but feel free to prove me wrong.

**Comment by RockyTV** [comment]
@KyleMcNutt I'm trying to readapt your code for my page. I copied what you wrote, but it messed up the entire page.

**Comment by KyleMcNutt** [comment]
@RockyTV You should keep in mind that I don't have _explicit_ references to the `flipclock.min.js` and `flipclock.css` though you will still need those. The only thing I changed was adding `class="center"` on the parent `<div>` to the FlipClock and adding the `below` class to the parent div surrounding the text. I also added the two CSS classes `center` and `below`. Can you be more descriptive when you say "it messed up the entire page"? From what you've posted here this is a very simple page.

**Comment by RockyTV** [comment]
http://rockytv.github.io/h1z1
style: http://rockytv.github.io/assets/style.css

**Comment by brianespinosa** [comment]
@KyleMcNutt I edited your codepen for @RockyTV in favor of not using absolute positioning. That is likely what @RockyTV is referring to as "breaking the page" since it is removing the elements absolute positioned elements from the flow of the page.

http://codepen.io/anon/pen/yyMBRR

The reason `text-align: center` was not working for you is because the default FlipClock div had a `width: 100%`. It needs to have a default width controlled by the content inside of it, in addition to a `display: inline-block`. I was only just now able to officially see that working now that I am back in front of my computer.

@RockyTV, let me know if that CSS works better for you.

**Comment by KyleMcNutt** [comment]
@brianespinosa Good catch on the width, my bad.

The absolute positioning was the reason that I listed my above link as not being the best solution.

**Comment by RockyTV** [comment]
@KyleMcNutt  @brianespinosa I copied your code, thanks, but now it wont align again! I don't know if it's jekyll messing up, but it wont align!

Also, just to note, it may look like that I've created that theme from scratch, but I didn't. I got from an open-source jekyll blog on GitHub.

**Comment by brianespinosa** [comment]
@RockyTV That is because your flipclock div still has a `width: 100%` on it, which is being inherited from the `.flip-clock-wrapper` class if you right click and inspect your code. You need to change the value on that class from `width: 100%` to `width: default` and it will center. I just changed it in the browser with your live site and it worked.

I am going to mark this issue closed.

**Comment by RockyTV** [comment]
Thanks for helping me out guys!

**Comment by brianespinosa** [comment]
@RockyTV You're welcome. :+1:

**Comment by RockyTV** [comment]
I should poke it tomorrow, didn't manage to get it working...

**Comment by brianespinosa** [comment]
You didn't change it in flipclock.css

**Comment by RockyTV** [comment]
Oh, I thought I had to change it in my stylesheet! Oh, lol.

**Comment by brianespinosa** [comment]
If you wanted to do it without editing the flipclock.css file, you would have to make your overriding CSS more specific. The easiest way to do that would be to combine the class styles for `.h1z1-clock` and `.flip-clock-wrapper` into `.h1z1-clock .flip-clock-wrapper' which would accomplish what you are trying to do.

Here's an article on CSS specificity you should check out. There are probably better ones but this was one I found real quick: http://www.smashingmagazine.com/2007/07/27/css-specificity-things-you-should-know/

And here is an article on how to use your browser to inspect the styles it is using to build your page so you can see which ones are actually in use by your browser and which ones are being overridden: http://www.sitepoint.com/inspect-element-troubleshooting-css-browser/

Both of those concepts are huge for you to have down and will allow you to troubleshoot most issues you are having without having to rely on someone to dig through and point them out for you. :)

**Comment by RockyTV** [comment]
Okay, thanks. Will read them and see if I can design my own theme for
Jekyll.

By the way, one question: if I call the jQuery function to set the HTML for
the clock div to empty when the countdown stops, would it work? (kinda hard
to test atm, on mobile)

**Comment by Zahinize** [comment]
Hi Alexandre,

For emptying or hiding the clock div when countdown stops, you can just
write this:

$(".clock").hide() or .empty()

i.e., hiding your selector div in stop callback of your flipclock api. You
can check flipClock library examples as well. I am sure one of these will
suit your need.

P.S.: Flipclock is fully compatible with jQuery so your every jquery api
will work :). Hope this helps.

Best Regards,
Zahin Omar Alwa

**Comment by ahoulgrave** [comment]
This worked just fine. Based on @brianespinosa 's answer.

http://codepen.io/ahoulgrave/pen/PNByqm

**Comment by betesh** [comment]
Thanks @ahoulgrave Saved me a lot of time.

**Comment by austinarchibald** [comment]
goodness gracious, @ahoulgrave ... hours of trying to center this damn thing. i was only missing the width: auto. css can be so frustrating sometimes. thank you!
