### ISSUE TITLE
Read the Docs API

### ISSUE THREAD

**Issue by objectivehtml** [objectivehtml/FlipClock#176]
One thing that would be great for the FlipClock.js API would be to post the all the API docs on Read the Docs. If anyone has any experience with generating documentation with Sphinx or Node.js to get the docs posted on Read the Docs would be much appreciated. I think in a perfect world the docs would be generated with Grunt/Node as html files that are then automatically updated on Read the Docs (via the git repo).

Let me know!

**Comment by brianespinosa** [comment]
I was just thinking about that the other day. I've used [Flatdoc](https://github.com/rstacruz/flatdoc) before and it worked well. I have not used Read the Docs before but I think we could easily set that up. It's been a while since I looked at their setup data.

**Comment by objectivehtml** [comment]
I looked into it last night actually it's pretty confusing IMO. I couldn't get sphinx setup without updating xcode or something...and I have yet to update to Yosemite so i couldn't get it to work at all (the installer that it). I looked it up, it's a known issue and I didn't have to time to keep hacking at it to get it fixed. And updating my OS isn't doable for me right now.

My only other solution was to use a JS/node compiler to generate the html. Once we get that all working I will go back through all the code comments and format it properly.

I have an account setup on Read the Docs already. I am happy to share the login if you can get the Flatdoc stuff to work. And for the record, I absolutely hate doc generators. Every single time I go to use one, it fails to ever work properly despite following the instructions. I've tried to use Sphinx at least 3 times. But at the same time, I feel like loads of people use them as well as most major projects so I feel like I should be able to get it to work, so I keep trying.

http://flipclock.readthedocs.org/en/latest/

**Comment by objectivehtml** [comment]
Another update to this post. I have tried jsdocs and it definitely isn't as good as I thought it would be. I am going to see if I can get sphinx running on my Vagrant machine to write the docs. I am just not linking the code format of the JS generators, or how the generated docs look.

If this wasn't so daunting of a task, I would consider writing something but there is no way I am going to do that.

**Comment by objectivehtml** [comment]
Closing this because docs are finished and built with jsdoc.
