### ISSUE TITLE
Making an everyday countdown limit with exception saturdays and sundays

### ISSUE THREAD

**Issue by Kristobal1969** [objectivehtml/FlipClock#177]
Hello,
Here is what I am trying to do with this nice looking flipclock. 
Every morning  from 9:00 AM
There is a deadline every morning at 9:00 AM.
All orders made after 9:00AM will be delivered the next day (except saturdays and sundays, closed)
I want to have a coundown telling the time remaining for ordering for today's delivery (after 9:00 AM fridays it will show the coundown until monday 9:00 AM)

How is it possible to implement that ?
I hope you can help
Thanks
Regards
Kris

**Comment by objectivehtml** [comment]
First, download the latest dev branch. My example is using the new version, which hasn't been officially released yet. If you look at the `countdown-to-new-years.html` example you will see where my example is derived. Pretty similar concept, except you need to reset the clock after it stops to another 24 hours interval.

Basically, you just need to define the deadline hour, which in your case in 9. If the current hour is greater or equal to 9, then the deadline has passed so +1 needs to be added to the future object. Once you have your date objects, its just a matter of calculating the difference (in seconds) and set the clock value. If 9am passes, the clock will reset.

	<div class="clock" style="margin:2em;"></div>

	<script type="text/javascript">
		var clock;

		$(document).ready(function() {

			var deadlineHour = 9, offset = 0;;

			// Grab the current date
			var currentDate = new Date();

			if(currentDate.getHours() >= deadlineHour) {
				offset = 1;
			}

			var futureDate = new Date(
				currentDate.getFullYear(), 
				currentDate.getMonth(), 
				currentDate.getDate() + offset, 
				deadlineHour
			);

			// Calculate the difference in seconds between the future and current date
			var diff = futureDate.getTime() / 1000 - currentDate.getTime() / 1000;

			// Instantiate a coutdown FlipClock
			clock = $('.clock').FlipClock(diff, {
				clockFace: 'HourlyCounter',
				clockFaceOptions: {
					countdown: true
				}
			});

			clock.face.on('stop', function() {
				// add 24 hours worth of seconds to the clock face
				clock.setFaceValue(24 * 60 * 60);
				clock.start();
			});
		});
	</script>

**Comment by objectivehtml** [comment]
I didn't read the part about Saturday or Sunday, but would can integrate that yourself. You will just have to modify my logic and add some additional conditionals to check to see the current day is saturday or sunday. If it is, just increase the offset by additional 2 (if sat) or 1 (if sunday).

**Comment by Kristobal1969** [comment]
Thanks a lot for this code. I am totally unable to integrate the right code about saturday and sunday. Could you do that for me ? I am more a designer than a progammer. I hope you can help adding the solution.
Thanks

**Comment by objectivehtml** [comment]
Closing this old thread. If anyone needs this for the new version, open a new issue.
