### ISSUE TITLE
SCSS file does not agree with compiled CSS file. 

### ISSUE THREAD

**Issue by igmcdowell** [objectivehtml/FlipClock#178]
I'm interested in customizing the clock size, and would rather work by changing one SCSS variable than hand-tweaking 30 css properties. I forked and set up grunt for building the CSS from the included SCSS file, but building with no changes to flipclock.scss resulted in numerous changes to flipclock.css. 

It seems like there's either a missing change to the SCSS file, or it's old/obsolete and should be removed from the repo.

Here's one example change in flipclock.css after rebuilding from flipclock.scss (there are many more):
```diff
.flip-clock-wrapper * {
-    -webkit-box-sizing: border-box;
-    -moz-box-sizing: border-box;
-    -ms-box-sizing: border-box;
-    -o-box-sizing: border-box;
-    box-sizing: border-box;
-    -webkit-backface-visibility: hidden;
-    -moz-backface-visibility: hidden;
-    -ms-backface-visibility: hidden;
-    -o-backface-visibility: hidden;
-    backface-visibility: hidden;
-}
+  margin: 0;
+  padding: 0;
+  line-height: normal;
+  -webkit-box-sizing: border-box;
+  -moz-box-sizing: border-box;
+  box-sizing: border-box; }
```

**Comment by brianespinosa** [comment]
Hi @igmcdowell!

Yes, the SCSS file is not actually being used to compile in the main branch. It was something added a few versions back that wasn't quite a 1:1 conversion of the CSS.

Take a look at #161 so you can see where we are going with this. I actually have grunt compiling from new SCSS files and some of the markup is getting refactored. In addition, the SCSS files will have variables associated and there will also be a couple other theme options, responsiveness, etc.

There is a 1.0 branch we are working on now. I have not actually pushed my working Grunt file that is doing all this, but there should be something of this in the 1.0 branch sometime this week. We're real close to what you are wanting to do out of the box... and a lot more.

I am going to go ahead and mark this one as closed in reference to #161

**Comment by objectivehtml** [comment]
Thanks @brianespinosa. You rock man.

**Comment by igmcdowell** [comment]
@brianespinosa thanks for the clarification. Just read through #161, it sounds great. Excited for the coming changes.
