### ISSUE TITLE
It has mistake in compiled CSS

### ISSUE THREAD

**Issue by westyby** [objectivehtml/FlipClock#179]
In SCSS look's like good, but in compiled CSS has some mistakes. http://joxi.ru/L21JRJyURxoZAX
line 260 /src/flipclock/css/flipclock.scss: background: linear-gradient(top, rgba(0, 0, 0, .1) 0%, rgba(0, 0, 0, 1) 100%);
line 335 /src/flipclock/css/flipclock.css: background: linear, top, rgba(0, 0, 0, 0.1) 0%, black 100%;
Compilatir losing word "-gradient"

**Comment by objectivehtml** [comment]
SCSS is getting rewritten. See the thread here.

https://github.com/objectivehtml/FlipClock/issues/161
