### ISSUE TITLE
Mobile WebKit has odd animation

### ISSUE THREAD

**Issue by kylejcorrigan** [objectivehtml/FlipClock#182]
I noticed that on mobile safari that the flip animation seems to look a little buggy with shadows.

**Comment by objectivehtml** [comment]
We are working on a new build, which is a complete refactoring of the code and scss. You can learn more about it here. https://github.com/objectivehtml/FlipClock/issues/161

I am sure @brianespinosa will be testing on mobile, as he is handling all the new responsive CSS. If you can provide any more information outlining the error, I am sure it would help him out.

**Comment by objectivehtml** [comment]
These changes have finally been integrated, and much more in the js-es6 branch. Closing this thread.
