### ISSUE TITLE
Options to add leading zeros?

### ISSUE THREAD

**Issue by coreyleedesigns** [objectivehtml/FlipClock#183]
Great plugin and flip animation! Just wondering if it's possible to add leading zeros for a general counter? So when display on a page it'll look like 0356 or something.

I'm setting the counter manually like clock.setTime(037842); but the leading zero is gone when view on page.

Thanks.

**Comment by objectivehtml** [comment]
The `minimumDigits` property is what you are looking for. If it doesn't work in the master branch, I know it works in the new dev branch which is a completely refactoring of the codebase. The dev branch is a breaking build though, a lot of things were refactored for the upcoming 1.0.0 release.

**Comment by coreyleedesigns** [comment]
Ahhh great! Thanks for the prompt reply, <code>minimumDigits</code> does work. Somehow it wasn't documented on the main page so I did not know that option is available. Thanks!

**Comment by objectivehtml** [comment]
Yeah, i have updated the docs in preparation for the new version. I have this property documented in the next release.
