### ISSUE TITLE
[Solved] Seconds counts wrong

### ISSUE THREAD

**Issue by Freakmeister** [objectivehtml/FlipClock#185]
Wanned to add a bug, but then fixed it. Wanna add this anyway:
I use FlipClock as a countdown. And I hook seconds from a div like this:
`var Seconds = $('.jsFlipClockSecondsHolder').html();`
`clock.setTime(Seconds);`
But the problem was that Seconds is a string. And plugin counted seconds wrong. This helped:
`var Seconds = $('.jsFlipClockSecondsHolder').html();`
`clock.setTime(parseInt(Seconds));`
I think this parseInt should be in plugin, you should add this in the future. Cheers.

**Comment by objectivehtml** [comment]
The next version of FlipClock allows for alphabetical clocks and hopefully even going to add decimal based clocks, so forcing an integer isn't really desirable for versatility. It could perhaps be implemented at the Flock.Face level, but that would up to each face to implement it.

I think what you have there is proper.
