### ISSUE TITLE
FlipClock Translation also in Catalan

### ISSUE THREAD

**Issue by JoanIzquierdo** [objectivehtml/FlipClock#188]
/**
- FlipClock Catalan Language Pack
  *
- This class will used to translate tokens into the Catalan language.
  *
  */
  
  FlipClock.Lang.Catalan = {
  
    'years'   : 'Anys',
    'months'  : 'Mesos',
    'days'    : 'Dies',
    'hours'   : 'Hores',
    'minutes' : 'Minuts',
    'seconds' : 'Segons'
  
  };
  
  /\* Create various aliases for convenience */
  
  FlipClock.Lang['ca']      = FlipClock.Lang.Catalan;
  FlipClock.Lang['ca-es']   = FlipClock.Lang.Catalan;
  FlipClock.Lang['catalan']  = FlipClock.Lang.Catalan;

}(jQuery));

**Comment by objectivehtml** [comment]
This language pack has finally been added to the v1 release, currently in the js-es6 branch.
