### ISSUE TITLE
Change Countdown To Be Based on Epoch Time Value?

### ISSUE THREAD

**Issue by apexmateria** [objectivehtml/FlipClock#189]
As it is the countdown gets refreshed each time a user re-visits the page.

I need the countdown to be the same for everyone regardless of time zone. I think having it countdown to an epoch code is a good solution for this.

http://www.esqsoft.com/javascript_examples/date-to-epoch.htm

Any idea how I can integrate this into my current code?

-------------------------------------

<html>
	<head>
		<link rel="stylesheet" href="./files/flipclock.css">

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

		<script src="./files/flipclock.js"></script>
	</head>
	<body>
	<div class="clock" style="margin:2em;"></div>
	<div class="message"></div>

	<script type="text/javascript">
		var clock;
		
		$(document).ready(function() {
			var clock;

			clock = $('.clock').FlipClock({
		        clockFace: 'DailyCounter',
		        autoStart: false,
		        callbacks: {
		        	stop: function() {
		        		$('.message').html('The clock has stopped!')
		        	}
		        }
		    });
				    
		    clock.setTime(220880);
		    clock.setCountdown(true);
		    clock.start();

		});
	</script>
	
	</body>
</html>

**Comment by Brotakuu** [comment]
I need the same thing. Did you ever find a solution?

**Comment by apexmateria** [comment]
Hey, ya I paid to have a really nice solution worked out for me. It still uses flipclock but you just go into the code and enter a date when the countdown will end. Works perfectly :D 

If you want the code download it here: 

https://www.sendspace.com/file/ht4mxd

FlipClock Custom.zip (70.85KB) <<<<<--- only click the blue download button, its the same color as the header. some ads might look like fake download buttons so watch out :D

Go into examples folder and edit base.php

Let me know how it works for you.

Peace
