### ISSUE TITLE
Countdown shows HH:MM:60?

### ISSUE THREAD

**Issue by mikeRead** [objectivehtml/FlipClock#193]
I think this is a bit of a bug the countdown is showing 2:60 instead of 3:00
![655f14a486c63c8899e2055c6856a066](https://cloud.githubusercontent.com/assets/3676392/6932743/7d7fcdc0-d7e3-11e4-8cf3-1c106c1c22eb.png)

**Comment by mikeRead** [comment]
I found a solution. the function getSeconds on line ~1550 of current release
```Javascript  
return Math.ceil(seconds); 
``` 
it should be 
```Javascript 
return Math.floor(seconds);
 ```

Thanks

**Comment by objectivehtml** [comment]
I would try the new version in the dev branch to see if that fixes your issues. The initialization syntax has changed slightly, but I am pretty sure that I have this fixed in the new build, which is a complete refactoring of the code.

**Comment by mikeRead** [comment]
Thank you, I had a feeling it didn't address the core problem. will try the dev branch

**Comment by objectivehtml** [comment]
Closing this thread, as this is old and new version of library should address this.

**Comment by mikeRead** [comment]
3 years later....

**Comment by objectivehtml** [comment]
Haha, long time coming :). Life happens, and didn't want this library to go by the wayside.

**Comment by mikeRead** [comment]
Haha totally understandable ; )
