### ISSUE TITLE
Clock stops flipping in Chrome on iOS while scrolling

### ISSUE THREAD

**Issue by james-tocc** [objectivehtml/FlipClock#197]
I've noticed that the clock seems to stop flipping in Chrome on iOS as you're scrolling down the page. Once you stop scrolling, the clock resumes flipping, but the clock is now off based on how long you scrolled for.

You can see this here https://orangechef.com where I've implemented the clock, but also on the example site at http://flipclockjs.com

**Comment by objectivehtml** [comment]
Thanks for pointing this out. I am not wondering if the issue in this thread is not the same as this one, technically speaking. Just making a note of this here but going to leave this open in case others can comment.

https://github.com/objectivehtml/FlipClock/issues/155

**Comment by wlekin** [comment]
i cant start the clock in ios
