### ISSUE TITLE
Display weeks.

### ISSUE THREAD

**Issue by ahmdrami** [objectivehtml/FlipClock#198]
How do I add weeks counter to the Flipclock? Is it possible? Any help would be great please.

**Comment by EralpB** [comment]
Yes and based on same tactic I want to add months, without weeks. What's the best way to approach this?

**Comment by jeanlescure** [comment]
ping

**Comment by techieshark** [comment]
@ahmdrami @EralpB @jeanlescure if you want to give the code I just committed (see above) a try, that'd be great. Thx.

**Comment by techieshark** [comment]
Here's a screenshot of an example that uses it (one problem you might notice is it gets long for small screens like on mobile):

![image](https://cloud.githubusercontent.com/assets/1072292/8588642/f79240fe-2660-11e5-90d3-08305f5a6cbc.png)

**Comment by ahmdrami** [comment]
Thanks :)

**Comment by jeanlescure** [comment]
awesome!

**Comment by ojas-sathe** [comment]
Thanks so much! I cloned your entire FlipClock directory onto my local machine and used your versions of src and compiled (and it defaulted to the days counter) -- anyone else get it working?

**Comment by objectivehtml** [comment]
This has been integrated into the library called the `WeekCounter` in the new v1 draft, currently on the js-es6 branch. There is also a YearCounter face now too.

**Comment by techieshark** [comment]
@objectivehtml that's great, thanks!
