### ISSUE TITLE
Increment Counter by specific Number, General counter increase by 5 0r 10

### ISSUE THREAD

**Issue by tatvasoft14** [objectivehtml/FlipClock#199]
I have implemented a Flipclock and my requirement is I want to increase my counter to 5 every 1 secs.

I have tried all the feasible solution.
###### 

<script type="text/javascript">

            $(document).ready(function() {
    var clock = new FlipClock($('.counter'), {
        clockFace: 'Counter',
        minimumDigits: 5
    });

    setTimeout(function() {
        setInterval(function() {
            clock.increment(10);
        }, 1000);
    });
            });
        </script>
###### 

Basic Req :

Total Counter Number  : 3600
Increase counter  : 6 per min

6 counter should increase every minute, i.e. 6,12,18,....

Can you please help ?

**Comment by objectivehtml** [comment]
I don't have an example of this on hand, but do you have an example of something you tried? There are quite a few ways to do this actually, really shouldn't be that hard with JS.
