### ISSUE TITLE
Safari Errors

### ISSUE THREAD

**Issue by sunerandgarcia** [objectivehtml/FlipClock#200]
I am not sure why i am getting an error on safari

https://prostudiolive.com/clock.php

Do you guys have an idea why? It works fine on Chrome.

**Comment by objectivehtml** [comment]
Look at the error console in Safari. Says "Invalid Date". Your date object isn't correct in Safari, likely the format. JS has pretty poor implementations across browsers when it comes to date formats in particular.

**Comment by naeemz** [comment]
To fix the "Invalid Date" issue in Safari, make your javascript/jquery date like following:

console.log ( new Date('2017-11-02'.replace(/-/g, "/")) );

Its because Safari cannot do it correctly is too much and a regex is overkill.
