### ISSUE TITLE
Using scale with browser resizing issue

### ISSUE THREAD

**Issue by alcibald** [objectivehtml/FlipClock#201]
I've managed to resize the flipclock successfully but when I resize the browser, the seconds digits will move to a new line if I reduce my browser's width. Any idea what I need to adjust to fix this?

![image](https://cloud.githubusercontent.com/assets/12150780/7366621/2e107ede-edcc-11e4-938b-d1d9b22cefe7.png)

**Comment by nataniko** [comment]
how you resize flipclock?

**Comment by brianespinosa** [comment]
@alcibald This is going to be handled in #161.

@nataniko, currently the easiest way to resize the clock is to use `transform: scale(1.x);` in your CSS on the clock container. You will not have to do it this way in the new version.
