### ISSUE TITLE
Clock stops flipping when not the active tab

### ISSUE THREAD

**Issue by d4nyll** [objectivehtml/FlipClock#202]
When I navigate to http://flipclockjs.com/ and switch to a new tab, and then return to the page later, the clock switches from say `07:30` to `09:12`. What I'd expect is for the flipping to continue even if it is not the active tab, so in my example, it'll change from `09:11` to `09:12`.

**Comment by KyleMcNutt** [comment]
See Issue #155 for the discussion on this.

**Comment by d4nyll** [comment]
@KyleMcNutt I did not see that issue but I believe this is a separate issue. That one is about the clock running slower when not the active tab, this one is about the numbers not updating while not the active tab.

**Comment by KyleMcNutt** [comment]
@d4nyll I believe this is the same issue. Since the countdown drifts while in a different tab then how would the numbers accurately continue to flip?

**Comment by d4nyll** [comment]
@KyleMcNutt In the other issue, as you've put it - the countdown drifts so it's inaccurate. Here, I'm not saying anything about accuracy, only that the numbers stops flipping when it's not the active tab, and so when I return to the tab, initially, the numbers are the same as when I navigated away from it.

**Comment by KyleMcNutt** [comment]
@d4nyll Correct, but would you rather have the clock flip inaccurately when it's not the active tab?

**Comment by d4nyll** [comment]
@KyleMcNutt No I wouldn't. But that's why there are separate issues for...separate issues! That issue tracks the inaccurate timing, and this issue tracking another thing!

**Comment by objectivehtml** [comment]
I haven't worked out a good solution for this yet. The correct solution requires HTML5 web workers. But the very nature of the way the web workers work makes it a little difficult to implement in a library such as FlipClock. If anyone wants to take a stab at it, feel free to grab the dev branch and make a pull request.

http://www.html5rocks.com/en/tutorials/workers/basics/

**Comment by objectivehtml** [comment]
As far as the accuracy goes, I have seen this too. It's more of a performance thing than the logic being wrong. I was doing research on this and didn't really find a lot other than there is a known variance, and with the amount of code that ran with each second, perhaps JS engines have a hard time keeping up. My only immediate thoughts would be to trim down the animation time a bit to be less than a second and see if that does anything.
