### ISSUE TITLE
Is possible get time from web server, not from client?

### ISSUE THREAD

**Issue by StreamThreader** [objectivehtml/FlipClock#206]
Hi
Your clock is very cool.
We have web site of project "NTP server in Odessa", we want javascript clock (preferable with milliseconds).
We use your clock for now, but this clock use time from client, is possible use ntp server as time source for high precision?
For example i found this project (https://github.com/majetzx/ntplite) it php ntp client for get time.

If clock can't get time from NTP server, it possible just get time from server on that web site runing?

**Comment by tainazao** [comment]
I would like to know if it's possible too...

**Comment by cam1883** [comment]
It looks like this is an old thread, but the answer is yes. I am using this in conjunction with a Urgent Care website to tell people when the next available time spot is open.  What you can do is say 
<?php 
date_default_timezone_set('America/Los_Angeles'); //Getting timezone for PST
$todaytime = date("Y-m-d h:i:s"); //What is today's date currently

$returnTime = '
<script>
$("#time").FlipClock({
			clockFace: "TwelveHourClock"
		});
		clock.setTime('.$todaytime.');
		clock.setCountdown(true);
)};
</script>
';
return $returnTime;
?>

**Comment by cam1883** [comment]
<?php 
date_default_timezone_set('America/Los_Angeles'); //Getting timezone for PST
$todaytime = date("Y-m-d h:i:s"); //What is today's date currently

$returnTime = '
<>
$("#time").FlipClock({
			clockFace: "TwelveHourClock"
		});
		clock.setTime('.$todaytime.');
		clock.setCountdown(true);
)};
<>
';
return $returnTime;
?>

**Comment by objectivehtml** [comment]
Old thread. Open a new issues if anyone still needs this on the newest version.
