### ISSUE TITLE
Milliseconds

### ISSUE THREAD

**Issue by gersonj13** [objectivehtml/FlipClock#210]
Hello, 
there is a way to show milliseconds?

**Comment by deven20377** [comment]
The same requirement here.
Is it possible to add / show milliseconds?

**Comment by BoffinbraiN** [comment]
I think having a millisecond counter would go against the purpose of using a flip-clock. The numbers couldn't flip fast enough! It would also be quite demanding on the CPU. Surely you'd be better off using a simple text counter.

**Comment by brianespinosa** [comment]
@gersonj13, @deven20377, thanks for your inquiry. @BoffinbraiN is correct. The numbers in the clock face would not flip fast enough. The CSS animation for the face could be updated, but that's probably beyond the scope of this project.
