### ISSUE TITLE
New Digits added to Counter clockFace Don't Flip

### ISSUE THREAD

**Issue by bengrosser** [objectivehtml/FlipClock#213]
When using the "Counter" clockFace, new added digits don't "flip", they only update their value. So, for example, if you start the counter at 9999 using setTime(9999) and then watch it go to 10000, the last digit, that last '0', only updates it value but it never flips when it does so. 

I'd appreciate a hint as to the workaround for this even if you don't have time to integrate a fix right now. Thanks!

**Comment by bengrosser** [comment]
Ok, I figured out what's going on here. The "play" class isn't getting added to the new digit because running was set to false. I wasn't using clock.start() in my code (which would have set running to true) because I didn't have to --- and because when using increment/decrement it doesn't seem like I should.

So not sure it's a bug and maybe I should have just been using start() all along, but it's a bit confusing.

**Comment by objectivehtml** [comment]
Fixed in the new v1 draft release in the js-es6 branch.
