### ISSUE TITLE
Counter clockFace shouldn't init with previousDigit

### ISSUE THREAD

**Issue by bengrosser** [objectivehtml/FlipClock#214]
If I start a counter at say 9995 then I get strange results on first load. The first value seen on the counter will be 8884 and then it will flip to 9995. On the Counter face, the expected behavior would be to see the current value of the counter and only see it change when the counter increments or decrements.

I can override this behavior by explicitly setting lastDigit = 0 in createList, but I'm sure there's a better way of doing that.

I'm also not convinced that when using the Counter face that it should flip on first load, and should only flip when it increments or decrements. Thoughts?

**Comment by MBarimah** [comment]
Did you manage to solve this issue, I am currently facing the same issue with the count's down, when I use a number like 100 it shows 199 at the beginning then 100 and then it starts going down. is there any way to stop the initial flip with the strange numbers?

for example in Daily counter, there is no flip at the beginning

**Comment by acm482** [comment]
I'm also experiencing this issue with counting down and navigating between bootstrap togglable tabs that have the countdown clocks inside them.

**Comment by QuietJam** [comment]
the official demo has this problem too,hope to be fixed .

**Comment by nmeynard** [comment]
So buggy...
When I init the fliper clock with 30 as a value, it display 21 !!!!!! ??????
So I tried to display 00 and then display time afterward, it displayed 09 !!!!!?????

Why does it takes the value it wants ? how to tell him "display 00" what is the randomed value for 00 ? 13457 ? 93839 ? ...................

So sad you did a nice job but ther's a fatal bug preventing from using it....

**Comment by objectivehtml** [comment]
This is fixed in the newest versions. js-es6 branch currently has the v1 draft release. Closing this issue.
