### ISSUE TITLE
Hungarian localization

### ISSUE THREAD

**Issue by lyahim** [objectivehtml/FlipClock#215]
Dear Contributors!

I Like this tool, because very useful simple and pretty :)
I have to make a hungarian version and I would like to share this with you.

FlipClock.Lang.English = {

```
    'years'   : 'Év',
    'months'  : 'Hónap',
    'days'    : 'Nap',
    'hours'   : 'Óra',
    'minutes' : 'Perc',
    'seconds' : 'Másodperc'    

};
```

FlipClock.Lang['hu']      = FlipClock.Lang.English;
    FlipClock.Lang['hu-hu']   = FlipClock.Lang.English;
    FlipClock.Lang['hungarian'] = FlipClock.Lang.English;

Best Regards,
Lyahim

**Comment by brianespinosa** [comment]
Thank you, @lyahim. I will integrate these for the upcoming release.

**Comment by szykov** [comment]
@brianespinosa 
check you have syntax error here:
https://github.com/objectivehtml/FlipClock/blob/17d9f3f1dd0da4918b3ff5dad4b03d737f9fb744/src/flipclock/js/lang/hu-hu.js#L24

**Comment by objectivehtml** [comment]
This is included in the new v1 draft, currently in the js-es6 branch.
