### ISSUE TITLE
module not found when using npm package

### ISSUE THREAD

**Issue by stevenmathews** [objectivehtml/FlipClock#220]
Not sure if anyone else is having a problem with this, but I've tried to use the npm package in two different projects to no avail.

**Comment by FutureKode** [comment]
Same issue here :(

**Comment by thirdender** [comment]
The [`package.json`](https://github.com/objectivehtml/FlipClock/blob/988e023/package.json) file is missing a [`main`](https://docs.npmjs.com/files/package.json#main) field. The `main` field should point to a JS file that will be included when the package is `required` by other code.

Adding the following to `package.json` fixes the issue (see thirdender/FlipClock#1):

    "main": "compiled/flipclock.js",

There's also talk about adding the CSS stylesheets to the `package.json` file, but nothing has been finalized. See [SO: "style" field in package.json](http://stackoverflow.com/questions/32037150/style-field-in-package-json) and [Use jQuery plugins with npm](http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm) (under "CSS File Path").

**Comment by brianespinosa** [comment]
@thirdender Thanks! This has been resolved in the forthcoming version of FlipClock.
