### ISSUE TITLE
Romanian localization

### ISSUE THREAD

**Issue by pax** [objectivehtml/FlipClock#222]
For whomever looks for a Romanian localisation (before it might get added to the master), look for `FlipClock.Lang.` in the source and add:
`function(){FlipClock.Lang.Romanian={years:"ani",months:"luni",days:"zile",hours:"ore",minutes:"minute",seconds:"secunde"},FlipClock.Lang.ro=FlipClock.Lang.Romanian,FlipClock.Lang["ro-ro"]=FlipClock.Lang.Romanian,FlipClock.Lang.romanian=FlipClock.Lang.Romanian}(jQuery)`

or just add the following code inside the `<script>` in the html page:

`FlipClock.Lang.Romana = {'years' : 'ani', 'months' : 'luni','days' : 'zile', 'hours' : 'ore','minutes' : 'minute', 'seconds' : 'secunde'};
FlipClock.Lang['ro'] = FlipClock.Lang.Romana; FlipClock.Lang['ro-ro'] = FlipClock.Lang.Romana; FlipClock.Lang['romana'] = FlipClock.Lang.Romana;`

**Comment by objectivehtml** [comment]
This has been integrated into the js-es6 branch, which is the new v1 draft.
