### ISSUE TITLE
add tag for 0.7.8

### ISSUE THREAD

**Issue by maruilian11** [objectivehtml/FlipClock#224]
would you please add tag for v0.7.8 so that we can add your lib on https://cdnjs.com **with git auto-update**. 
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5574

**Comment by PeterDaveHello** [comment]
https://github.com/objectivehtml/FlipClock/commit/592665ec6671d7560bce72da33ee494c0142f644

**Comment by objectivehtml** [comment]
Clos
