### ISSUE TITLE
Is not centered with bootstrap row col-XX-12 block-center

### ISSUE THREAD

**Issue by z4nsh1n** [objectivehtml/FlipClock#236]
It seems not possible to center the clock with bootstrap or margin: 0 auto; or any other method I could find in the internet for centering horizontally.

**Comment by BoffinbraiN** [comment]
I'll vote for this one too. The CSS for the flipclock specifies that the container must be 100% width, and the numbers float to the left, which makes it quite fragile for what we want. I worked around it by determining the width of the DailyCounter was 620px and writing some overriding CSS to specify that along with auto-margins. If the whole clock could be done with inline-blocks instead, that would be awesome.

**Comment by brianespinosa** [comment]
@z4nsh1n, @BoffinbraiN Agreed. The updated styles will allow the clock to be centered. I am actually planning on making the main container `display: inline-block` so it is possible to display the clock in a container with centered text and have it inherit that.

This will be part of #161
