### ISSUE TITLE
Responsive clock on Mozilla Firefox

### ISSUE THREAD

**Issue by artprojectgroup** [objectivehtml/FlipClock#238]
Hi. Thanks a lot for your great job.

Can you review your responsive CSS to make compatible with Mozilla Firefox?

Kind regards.

**Comment by cybersholt** [comment]
Someone will probably point you to use the zoom transform, I would imagine there is a better way

**Comment by brianespinosa** [comment]
@artprojectgroup This is going to be addressed in #161.
