### ISSUE TITLE
Dependencies on Helvetica and Helvetica Neue

### ISSUE THREAD

**Issue by BoffinbraiN** [objectivehtml/FlipClock#239]
The Flipclock CSS specifies the clock should use the Helvetica Neue or Helvetica font, but does not specify where the browser should get these fonts from. Most browsers will fall back on using sans-serif (Arial).

**Comment by brianespinosa** [comment]
@BoffinbraiN in the new styles there will be a SASS variable where you'll be able to specify your own font stack. There will also be other clock face themes. Probably 2-3 to start. You'll be able to duplicate one of those template files and compile your own face theme with whatever font stack you'd like. Closing as this is handled in #161
