### ISSUE TITLE
Customizable and Relative Font Sizes

### ISSUE THREAD

**Issue by BoffinbraiN** [objectivehtml/FlipClock#240]
The Flipclock CSS specifies all font sizes in pixels, and uses `!important` to force those sizes. If a user wants to change the size of the clock, they have to hack the CSS file and change lots of numbers directly.

A more elegant solution would be to specify the font size of the container once, and use `em` units for the rest, so if someone chose to change the font size of the clock, everything else will scale up or down proportionally. In addition, an option to set the font size from the JS API would make it even more flexible with no CSS hacking required.

**Comment by BoffinbraiN** [comment]
Pull request: https://github.com/objectivehtml/FlipClock/pull/242

**Comment by brianespinosa** [comment]
@BoffinbraiN Thanks for your work on this. I will take a look at it... but there is going to be an update to the markup and therefore the overall styles ( #161 ). The new clock will be responsive and use relative sizing throughout.
