### ISSUE TITLE
Language es-es.js

### ISSUE THREAD

**Issue by matudelatower** [objectivehtml/FlipClock#243]
in https://github.com/objectivehtml/FlipClock/blob/master/src/flipclock/js/lang/es-es.js

```
FlipClock.Lang.Spanish = {      
        'years'   : 'A&#241;os',
        'months'  : 'Meses',
        'days'    : 'D&#205;as',
        'hours'   : 'Horas',
        'minutes' : 'Minutos',
        'seconds' : 'Segundo'   
    };
```

'seconds' : 'Segundo' should be

```
'seconds' : 'Segundos'
```

'days'    : 'D&#205;as', should be 

```
'days'    : 'D&#237;as',
```

this is the correct translation

**Comment by jaschaio** [comment]
Just came here to tell the same. If everything is plural, seconds should be plural as well. Currently its singular

**Comment by brianespinosa** [comment]
Gracias, @matudelatower. I will handle these changes for the newest release.

**Comment by objectivehtml** [comment]
This has been integrated into the new v1 draft. I am not sure about the HTML entities though. None of the other languages have that. Its just the unicode characters. I'd rather not change it for 1 language if there isn't a reason for it, when all the other languages aren't that way. I only speak english, so I just differ to the contributors for the language dictionaries.
