### ISSUE TITLE
Refresh page when countdown stops

### ISSUE THREAD

**Issue by tulasikrishna6** [objectivehtml/FlipClock#253]
Hello,
Thanks for the very useful plugin, I looking to refresh the page when the click countdown stops. Is there a way to do this in this plugin?

**Comment by brianespinosa** [comment]
Hello, @tulasikrishna6. There are [callbacks available](http://flipclockjs.com/#callbacks) for FlipClock. Take a look at the examples folder for the `countdown-stop-callback.html` which has a working example of the `stop` callback.
