### ISSUE TITLE
FlipClock Black Anomaly (Second Countdown)

### ISSUE THREAD

**Issue by LoganLehman** [objectivehtml/FlipClock#255]
Hi, 

We are experiencing an issue where on Chrome Version 47.0.2526.111 (64-bit) we are experiencing a flashing anomaly when the clock numbers flip. We do have custom CSS applied to the clock. Let me know if it is needed to diagnose.

![flipclockerror](https://cloud.githubusercontent.com/assets/1081678/12590466/074627f4-c418-11e5-9c72-c7a84b9ed5bb.jpg)

Best Regards,

Logan B. Lehman

**Comment by brianespinosa** [comment]
Hello, @LoganLehman. Do you have a public link to this page for me to check out?

**Comment by LoganLehman** [comment]
@brianespinosa, Unfortunately the public link no longer contains the countdown, as the grand opening for this has been completed.

**Comment by brianespinosa** [comment]
@LoganLehman, thanks for the reply. I have a feeling I know what might have been causing this, which I have addressed in the new release. I am going to close this issue out.
