### ISSUE TITLE
issue Internet Explorer 11 windows 10

### ISSUE THREAD

**Issue by samIntegrateur** [objectivehtml/FlipClock#259]
Hello, thanks for this plugin.

I have noticed a weird issue in the bottom part of the card. It happens in Internet Explorer 11 on Windows 10. I have tried in Windows 7/8 and it's ok, so it's strange.

I wonder if it's connected to https://github.com/objectivehtml/FlipClock/issues/36

![capture](https://cloud.githubusercontent.com/assets/6340668/13078395/eea62e3a-d4be-11e5-800c-3ee993ec1892.PNG)

**Comment by brianespinosa** [comment]
Hi, @samIntegrateur. Thanks for the report. Could you possibly put together an example of this error in Codepen?

**Comment by Merryweather** [comment]
Any news here?
Can be reproduced when watching this site http://flipclockjs.com/faces/counter in IE10/IE11 on Windows 10. Works good in IE9,

**Comment by himma** [comment]
Heya

If you remove backface-visibility property in file flipclock.css on rows 9 to 13, everything starts to work on Internet Explorer 11 aswell! :)

In other words, remove the text that is in bold below:

source: flipclock.css 
`/* Get the bourbon mixin from http://bourbon.io */
/* Reset */
.flip-clock-wrapper * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -o-box-sizing: border-box;
    box-sizing: border-box;
    **-webkit-backface-visibility: hidden;
    -moz-backface-visibility: hidden;
    -ms-backface-visibility: hidden;
    -o-backface-visibility: hidden;
    backface-visibility: hidden;**
}`

**Comment by objectivehtml** [comment]
I have the backface-visibility removed in the upcoming v1 release, currently the `js-es6` branch. Closing this thread because v1 will be released this week with this fix.
