### ISSUE TITLE
Many flipclocks in a single page not working

### ISSUE THREAD

**Issue by ramanth139** [objectivehtml/FlipClock#260]
@Giuseppe-Mazzapica : want multiple flip clocks in a single html page . But only the last flipclock is working. 
[specifically I am using daily-counter-countdown.html ]
![multi_flipclocks](https://cloud.githubusercontent.com/assets/11781268/13403311/60161082-df3a-11e5-91a5-2dbd0f8751a5.png)

**Comment by brianespinosa** [comment]
Hello, @Giuseppe-Mazzapica. The example page you are referencing only has a single countdown clock on it, so I am not sure where the other two came from in your screenshot. If you want an example of how to initialize more than one countdown clock on a page and with different parameters, you should take a look at the `multiple-instances.html` example instead.
