### ISSUE TITLE
Clock keeps running and invokes stop callback after stopping

### ISSUE THREAD

**Issue by r-debashis** [objectivehtml/FlipClock#262]
Flipclock Version: 1.1
Browser: Chrome Version 48.0.2564.116
clock = $timerdiv.FlipClock({
    autoStart: false,
    countdown: true,
    stop: function () {
        console.log("callback function at: " + (new Date()).getTime());
    }
});
clock.setTime(15);
console.log("clock started at: " + (new Date()).getTime());
clock.start();

The first console log appears after 15 secs as expected, after which it keeps getting invoked every second. Is there a workaround?
I tried both flipclock.js and the flipclock.min.js.
Apparently this was an issue sometime back as well with the minified js.
Here is the console output:
clock started at: 1457248957646
VM467:77 callback function at: 1457248971647
VM467:77 callback function at: 1457248972646
VM467:77 callback function at: 1457248973647
VM467:77 callback function at: 1457248974647
VM467:77 callback function at: 1457248975647
VM467:77 callback function at: 1457248976647
VM467:77 callback function at: 1457248977647
VM467:77 callback function at: 1457248978647
VM467:77 callback function at: 1457248979646
VM467:77 callback function at: 1457248980647
`

**Comment by r-debashis** [comment]
Forgot to specify the jquery version.
JQuery 1.12.1

**Comment by objectivehtml** [comment]
Closing this old thread. Library has been completely rewritten. This should no longer be an issue.
