### ISSUE TITLE
Provide Typescript definition file to use flipclockjs in typescript

### ISSUE THREAD

**Issue by janknobloch** [objectivehtml/FlipClock#263]
Hey, thanks for your great project in first place.

I'd love to see a typescript definition descriptor to use flipclock inside of typescript.

Cheers
Jan

**Comment by blove** [comment]
@janknobloch, I needed to implemented the FlipClock.js library using TypeScript and wrote some basic interfaces for this. However, it would be great to have a flipclock.d.ts definition file in DefintelyTyped (and thus typings).

```
interface IFlipClockConfig {
  autoStart?: boolean;
  countdown?: boolean;
  callbacks?: {
    destroy?: Function,
    create?: Function,
    init?: Function,
    interval?: Function,
    start?: Function,
    stop?: Function,
    reset?: Function
  };
  classes?: {};
  clockFace?: string;
  defaultClockFace?: string;
  defaultLanguage?: string;
};

interface IFlipClock {
  start: Function;
  stop: Function;
  setTime: (time: Date) => IFlipClock;
  setCountdown: (countdown: boolean) => IFlipClock;
  getTime(): Date;
};

interface IFlipClockStatic {
  new (digits: number, config?: IFlipClockConfig);
};

interface JQuery {
  FlipClock?: (digits: number, config?: IFlipClockConfig) => IFlipClock;
};
```

**Comment by janknobloch** [comment]
@blove thanks for providing your interfaces.
I'm struggeling in the moment to get flipclock running with typescript / angular 2 at all, my container isn't showing up at all.
I did use the following code:

`private flipClock:any; `
`
//init clock inside constructor of my component

      this.flipClock = new FlipClock(jQuery('.your-clock'), {
        clockFace: 'HourlyCounter',
        autoStart: false,
        callbacks: {
        	stop: function() {
        		console.log('The clock has stopped!')
        		//call lecture timer here
        	},
        	start: function() {
        		console.log('The clock has started!')
        		//call lecture timer here
        	},
        	reset: function(){
        		console.log('The clock has been resetted!')
        		//call lecture timer here
        	}
        }
        });`

while also importing ``<script src="node_modules/flipclock/compiled/flipclock.js"></script>
      <link rel="stylesheet" type="text/css" href="node_modules/flipclock/compiled/flipclock.css">``

than I added a div in my template:
`<div class="your-clock"></div>`

Any suggestions? Im going to try to create a plunker to see if i can figure out my problem. (i thought maybe its a jquery problem so the dom does not get manipulated..)

**Comment by blove** [comment]
@janknobloch, A plunker would definitely help, but I would suggest that you look at some of the directive implementations for FlipClock that people have posted online. Just search for "ng flipclock" and check out the top 2 results:

https://github.com/dolanmiu/ng-flipclock
https://github.com/stevermeister/angular-flipclock/blob/master/index.html

**Comment by janknobloch** [comment]
@blove,
thanks for your fast replies, i could figure out my problem according to angular 2.
Just for the other peeps they might encounter this problem.

I had to call my flipclock initialization inside of the ngOnInit() [ngOnInit-Reference](https://angular.io/docs/js/latest/api/core/OnInit-interface.html#!#stq=ngOnInit&stp=1) method not inside the constructor. 

In addition I used the ElementRef class [ElementRef-reference] (https://angular.io/docs/ts/latest/api/core/ElementRef-class.html) injected in my component to access my flipclock dom element and jquery with replaceWith() to inject it.

Seems everything is working fine now. If i find some time ill attach a plunker.
Cheers
Jan

**Comment by ztfong1982** [comment]
@janknobloch 
May i know how you actually call flipclock inside of the ngOnInit and how to used with ElementRef?
I am just starting to learn Angular 2 recently

**Comment by kwameboateng** [comment]
@janknobloch could you share how you managed to link this to your angular nativescript/typescript?
@ztfong1982 
Thanks

**Comment by objectivehtml** [comment]
Going to close this thread. I don't use Typescript currently with any of my projects. I just rewrote this entire library for ES6 and completely rewrote all the classes, so all this will be obsolete in the new version. Not sure how much its needed if you can just import/extend the ES6 classes. Feel free to re-commit this code for the new version in the js-es6 branch. Going to merge to master soon, and make this v1 of the library. Will work with webpack and npm all the latest stuff.
