### ISSUE TITLE
Trying to start timer when countdown already at 0

### ISSUE THREAD

**Issue by dantahoua** [objectivehtml/FlipClock#267]
As soon as I want to use the "Countdown" face I struggle with his problem.
`Quizz.prototype.bind = function(){
   this.clock = $('#Compteur').FlipClock(10,{autoStart: false, countdown:true, clockFace: 'Counter'});
};`
And Then:
`Quizz.prototype.TimerPrepare = function () {
    this.clock.setTime(60);
};`
And then:
`Quizz.prototype.TimerStart = function () {
   this.clock.start();
};`
Note that if I use 'MinuteCounter', there is no problem... But I just want seconds!! And sometime 3 digits for seconds! (Like 180sec timer)...
Any idea?

**Comment by dantahoua** [comment]
Seems I have to use this but when I use this the counter do not stop when reaching 0, it continue backwards after reaching zero...
`var timer = new FlipClock.Timer(clock, {
					callbacks: {
						interval: function() {
							clock.increment();
						}
					}
				});`

**Comment by dantahoua** [comment]
Very weird stuff:
If I try the given example in my browser localy (simple-countdown-autostart.html), the counter is working but taking the same code in codepen do not work!!! Am I missing something?
Here is the codepen: [](http://codepen.io/dantahoua/pen/PNRLJZ)

**Comment by objectivehtml** [comment]
This is no longer an issue with the newest version. Closing this old thread. Open a new one if you are still having issues with the new version on the js-es6 branch.

**Comment by dexter0323** [comment]
You just need to specify an stop call back when you initialize the clock and it will stop in 00:00
    
    clock = $('.clock').FlipClock(diff, {
        clockFace: 'DailyCounter',
        countdown: true,
        callbacks: {
            stop: function() {
                //Trigger when countDown is over
            }
        }
    });
