### ISSUE TITLE
Bower install not latest version

### ISSUE THREAD

**Issue by ahoulgrave** [objectivehtml/FlipClock#269]
bower install objectivehtml/FlipClock --save
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower FlipClock#*               cached git://github.com/objectivehtml/FlipClock.git#0.7.7
bower FlipClock#*             validate 0.7.7 against git://github.com/objectivehtml/FlipClock.git#*
bower jquery#1.9.1 - 2          cached https://github.com/jquery/jquery-dist.git#2.2.3
bower jquery#1.9.1 - 2        validate 2.2.3 against https://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower flipclock#^0.7.7         install flipclock#0.7.7
bower jquery#1.9.1 - 2         install jquery#2.2.3

flipclock#0.7.7 bower_components\flipclock
└── jquery#2.2.3

jquery#2.2.3 bower_components\jquery

Then, in spanish lang: 

'seconds' : 'Segundo'

Whilst in your master branch its:

'seconds' : 'Segundos'

**Comment by brianespinosa** [comment]
Hello, @ahoulgrave... you may need to update your fork as needed to run bower. We will be using Gulp in the 1.0.0 version that we are in the process of working on now. I am going to close this issue out as a will not fix.
