### ISSUE TITLE
frontend counter glitch on some environments

### ISSUE THREAD

**Issue by verybigelephants** [objectivehtml/FlipClock#274]
hello,

i know this is a very poor bug reports, but some user has sent this screenshot to me and i just can't reproduce the issue on my device

![mobilmarket](https://cloud.githubusercontent.com/assets/3118985/15747377/b8b85738-28da-11e6-9f7c-a9e74b4dbebe.jpg)

on my computer it looks more like this 

![mobilmarket_good](https://cloud.githubusercontent.com/assets/3118985/15747379/bca64fbc-28da-11e6-804e-f9660bf51a49.png)

does anybody have **any** idea on why would this happen?

i initiate the plugin like this 

```
var clock = $('.countdown-clock').FlipClock( {1465974000-time()} , { 
            language:'sk-sk',
            clockFace: 'DailyCounter',
            countdown: true,
            showSeconds: false
        });
```

the curly brackets syntax is a server-side smarty. it prints some time, at this time of posting it's 1098017

**Comment by avranu** [comment]
I'm not sure if it's any help to you in debugging, but I got that behavior (with the dashes) when using a negative time. For instance:
$('...').FlipClock( -500 );

**Comment by objectivehtml** [comment]
This should be fixed in the branch, js-es6 which is a completely rewritten version of the library. Closing this old thread. Open a new one if you are still having issues with the new version.
