### ISSUE TITLE
Prevent line-wrap

### ISSUE THREAD

**Issue by fgenoese** [objectivehtml/FlipClock#275]
I am using FlipClock in an Ionic app, which forces me to scale it using:

```
.my-wrapper {
    zoom: 0.54;
    -webkit-transform: scale(.54);
}
```

This works as intended on Android/Chrome devices but not on iOS/Safari devices. This is how it looks like:

<img width="271" alt="Android" src="https://cloud.githubusercontent.com/assets/6893619/15931862/b5135fc2-2e59-11e6-8273-7e59860247c3.png">
<img width="226" alt="iOS" src="https://cloud.githubusercontent.com/assets/6893619/15931864/b6613b9c-2e59-11e6-8d29-0beaf17c0648.png">

The problem seems to be "zoom: 0.54", but if do not zoom, FlipClock automatically creates two lines, no matter how much I scale. Any idea how to fix this?

<img width="205" alt="zoom = 1" src="https://cloud.githubusercontent.com/assets/6893619/15931972/2e091f52-2e5a-11e6-9e98-b973654d6646.png">

**Comment by brianespinosa** [comment]
@fgenoese I don't recommend using `zoom` in this case. Using `transform: scale(.54)` is the solution you want. You'll want to add in some media queries to scale down further on smaller screens to avoid the wrap.

**Comment by fgenoese** [comment]
The thing is: It wraps in two lines **without** having reached the screen width (see above, 3rd screenshot), if I don't use zoom. Therefore, scaling further does not help...

**Comment by brianespinosa** [comment]
@fgenoese do you have a link to a location where this can be tested?

**Comment by objectivehtml** [comment]
Closing this old thread. Open a new thread for the new version if this is still an issue.
