### ISSUE TITLE
Remove first digit in list array on a countdown counter when it reaches zero

### ISSUE THREAD

**Issue by schester44** [objectivehtml/FlipClock#277]
I'm trying to remove/hide the digit on a counter when it reaches zero during countdown. Using a[ modified version of this code ](https://github.com/objectivehtml/FlipClock/issues/91), i've successfully created a counter that counts both up and down depending on the supplied value to `factory.increment()` or `factory.decrement()`. My issue is when the clock decrements from $1,000 to say $999, it reads as $0,999. 

I'm wondering how to remove the first value so it reads as $999 instead of $0999. I've messed around with `getTime().digitize`, `createList`, `appendDigitToClock`, `minimumDigits` and more but have yet to figure out how to do what i'm trying to do. Am I overlooking something or is this more complex then it seems?

**Comment by schester44** [comment]
[here is my code,](http://pastebin.com/07S3Qvum) and I roll the counter using the code below (`counter.roll(int)`)

`        var counter = $('#test').FlipClock(1001, {
            clockFace: 'Cash'
        });

        counter.roll(998);`

**Comment by objectivehtml** [comment]
This will have been fixed in the new v1 draft release on the js-es6 library. the digitizer was completely rewritten and has unit tests. Closing this old thread.
