### ISSUE TITLE
How to restart timer every 24 hours for specific time zone?

### ISSUE THREAD

**Issue by fanopolis** [objectivehtml/FlipClock#278]
Question. Hopefully it's possible with FlipClock.

I want a timer on my site that counts down to 13:00 UCT time every day.

When it's 13:00 UCT, it starts to count down 24 hours again.

What's the code I need to use? It could involve some PHP, I don't mind.

Thank you!

**Comment by objectivehtml** [comment]
This kinda outside the scope of the library and since its an old thread, I'm closing it. The library has been completely rewritten so if anyone needs this with the new version, open a new issue.
