### ISSUE TITLE
Factory.time.time value is not equal to the shown value

### ISSUE THREAD

**Issue by kuzditomi** [objectivehtml/FlipClock#279]
Hi!

First of all, thanks for the awesome library!
You can reproduce the issue on http://flipclockjs.com/ as well, just call `clock.stop()` and see the value of `clock.time.time`. It is 1 second after the shown value.

The reason of that is that the Face objects in `flip` methods create `time` value before calling base. Incrementation happens in base, but it display the received `time`.
I could fix it by passing just the display methods for base, but some kind of MVC pattern could be useful here :)

Thanks!
Tomi

**Comment by objectivehtml** [comment]
This should be fixed in the new js-es6 branch of the library. I completely rewrote this library, and by the sounds it, I have tested for this and it should be fixed. Open a new issue if you ever use the new version of the library.
