### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by fmp777** [objectivehtml/FlipClock#280]
![image](https://cloud.githubusercontent.com/assets/2659615/16357754/789fdd6c-3abc-11e6-8222-b92dd26806ce.png)

Thats flipclockjs.com in its own process and my implementation of it in its own process, both left to run over night.

**Comment by fmp777** [comment]
This may just be a bug in chrome?  I tested a canvas based "flipclock" that had nearly exact same animation as flipclock, and by morning, memory usage was 17gb!!!  

FlipClockJS seems to stick around 1.8-2.4gb range

If I can trust this memory addon in Firefox memory usage doesn't exceed 15mb

(all tests done on mac so far)

**Comment by fmp777** [comment]
For reference, remove flipclock from my custom page and it stays a steady 200mb
![image](https://cloud.githubusercontent.com/assets/2659615/16363595/6398b81e-3b8c-11e6-828c-a779133edd6f.png)

**Comment by fmp777** [comment]
Well guess I was wrong, it did go above 2.6
![image](https://cloud.githubusercontent.com/assets/2659615/16384060/d9a3241e-3c44-11e6-85e9-440dc3ebd1c3.png)

**Comment by fmp777** [comment]
![image](https://cloud.githubusercontent.com/assets/2659615/16423882/1e84a9d2-3d1b-11e6-847e-61f7dd171605.png)

**Comment by fmp777** [comment]
Tests on Windows latest chrome show much better memory management. No leak that I can see as of yet.  Page runs between 40-80mb.  

Tests on Safari latest El Capitan show the SAME memory leak (not surprising, its webkit engine, same as chrome).  

Tests on Firefox latest for mac show the best memory usage at around 10-20mb, no leak.

**Comment by fmp777** [comment]
After a few hours, it seems windows chrome also has the leak.  up to 420mb now

**Comment by qoomon** [comment]
Same Problem

**Comment by objectivehtml** [comment]
This is an interesting post. Just getting back to it after a long time. I rewrote the library completely with ES6 classes and compiling with Rollup for UMD and all the latest stuff. I wonder if this still an issue. I don't see it in my profiling in the testing of the new js-es6 branch.
