### ISSUE TITLE
Animation not displaying on jquery v2

### ISSUE THREAD

**Issue by avranu** [objectivehtml/FlipClock#281]
Using jquery 2.1.8, the flipdown animation doesn't display properly. It looks almost like the element to be flipped down has the wrong z-index, and is being flipped behind the next number... or only part of the animation is playing. Example:

![countdown](https://cloud.githubusercontent.com/assets/20191191/16426478/2d28ce0c-3d37-11e6-98e7-f48ee67890a3.jpg)

When switching to jquery 1.8.0, I get the expected behavior. I tested the examples on github and your site to be sure. Everything else about the plugin works fine on v2.x, but not the top animation.

Anyone have any idea how I can resolve this? I'd love to use this plugin, as opposed to some other countdown timer, but I'd like the animation to work in my current environment.

Thanks!

**Comment by avranu** [comment]
Still haven't figured out how to resolve this issue. However... I have managed to make the clock look acceptable - without the flipping effect - using the following css:

.flip .shadow, .flip .flip-clock-before { display: none; }

This hides the weird behavior and causes the clock to just switch between numbers rapidly, like a "normal" clock. If anyone has any insight into getting the actual flip behavior to work on jquery 2.x, please let me know. Thanks!

**Comment by brianespinosa** [comment]
@avranu The animations should be happening via CSS so should not have anything to do with javascript or jquery. All that is happening with javascript are the classes being applied to trigger the flipping. Are you trying to trigger the animations with jquery? Do you have a working example of this issue?

**Comment by avranu** [comment]
Hi Brian,

Thanks for the comment. I HAD a working example, where swapping out jquery in the google cdn caused the display issue... but now I'm having trouble recreating it. 

What I CAN do is recreate the problem irrespective of the jquery version. It seems to be (at least) a problem with the flipclock version in the cloudflare cdn. Here's a working demo of the problem:
http://jess-mann.com/flipclock/cloudflare.html

The css on flipclockjs.com, and on github, seem to work without issue:
http://jess-mann.com/flipclock/local.html

Anyway... glad to have it working. 

Thanks!

**Comment by brianespinosa** [comment]
@avranu Hmm... it appears that the markup and the way the class names are being fired in that CDN version are what is causing the problem. It's missing the part where the number flips down it looks like.

We'll let @objectivehtml know about this so he can look at getting an interim updated version of the JS provided to the Cloudflare CDN.

Thanks for tracking down the problem.

**Comment by objectivehtml** [comment]
I will update the CDN in the upcoming release. Closing this thread because all this is moot in the new version. jQuery isn't even used anymore.
