### ISSUE TITLE
3 digit is not showing for days

### ISSUE THREAD

**Issue by beatfreaker** [objectivehtml/FlipClock#282]
I want to set counter for 100 days but when i use following configuration it is not showing 100 days

``` js
clock = $('.clock').FlipClock({
        clockFace: 'DailyCounter',
        autoStart: false,
        callbacks: {
            stop: function() {
                setMessage();
            }
        }
    });
clock.setTime(3600*24*100);
```

it shows count down as following

![image](https://cloud.githubusercontent.com/assets/4180238/16497260/a4e8e098-3f13-11e6-8b81-051afc99a25b.png)

**Comment by sdwh** [comment]
clock = $('.clock').FlipClock(**3600*24*100,**{
        clockFace: 'DailyCounter',
        autoStart: false,
        callbacks: {
            stop: function() {
                setMessage();
            }
        }
    });


it will be fine

**Comment by jamespatterson** [comment]
I can confirm initializing with the correct time in the constructor does fix the problem. It appears the layout is only calculated once, so the max digits must be planned in advance.

**Comment by objectivehtml** [comment]
Fixed in the latest version. Closing this old thread. Check out the js-es6 branch or wait for it to get merged to master. OPen a new issue for the new version if you are still having trouble.
