### ISSUE TITLE
Does not count time correctly in Safari

### ISSUE THREAD

**Issue by gradosevic** [objectivehtml/FlipClock#286]
When used in Safari it shows correct time when page is loaded. However, when you go to other tab and switch back to FlipClock tab later, it shows wrong time. It looks like that somehow page freezes when it's out of the focus and restores back when it's in focus again.

**Comment by objectivehtml** [comment]
This has been fixed in the new js-es6 branch which is the official v1 draft. It now uses requestAnimationFrame loops to handle the animation. This should prove to be a much better handling of the performance, and the handling for inactive tabs has been improved as well.
