### ISSUE TITLE
"Invalid CSS property declaration" `.flip-clock-wrapper.clearfix { *zoom: 1; }`

### ISSUE THREAD

**Issue by Joshfindit** [objectivehtml/FlipClock#288]
Safari and https://jigsaw.w3.org/css-validator/#validate_by_input report that 

`.flip-clock-wrapper.clearfix { *zoom: 1; }`

is an invalid declaration.

Chrome doesn't seem to mind, however.

**Comment by objectivehtml** [comment]
This has been removed in the newer versions. Closing this old thread.
