### ISSUE TITLE
CSS minified version on cdnjs, animation glitch

### ISSUE THREAD

**Issue by cobaltway** [objectivehtml/FlipClock#289]
https://cdnjs.com/libraries/flipclock/0.7.8

The bottom part of the clock does not animate on my chrome browser when I use the minified version of the css presents on cdnjs.

No problem when using the normal version.

**Comment by Geczy** [comment]
Oh that's why that was happening, weird. Glad to know the normal version works

**Comment by oslerw** [comment]
I can confirm the behaviour on both Firefox 49.0.2 and Chrome 54.0.2840.71. Moving to the non-minified version fixes the animation.

**Comment by objectivehtml** [comment]
This is fixed in the new version, and latest versions of Chrome. Closing this old thread.

**Comment by Dror-Bar** [comment]
@objectivehtml 
My experience is quite different.
With version 0.7.8, when using the minified version the bottom animation is bugged. I have to use the non minified version for it to animate properly.
