### ISSUE TITLE
Console logging every second?

### ISSUE THREAD

**Issue by shoxter** [objectivehtml/FlipClock#293]
I'm not sure why, but FlipClock seems to be logging the timestamp every second to the console.

Can this be disabled?

**Comment by rgreer4** [comment]
This was a quickie use for me, so I just commented out the two "console.log()" calls...thats stops the yapping.   (Ideally, defaults off, with an option to enable....but doesn't look like this has had any activity in the last year...)

**Comment by objectivehtml** [comment]
This was an issue with the old version. The console.log was compiled in there. It has been removed in the new version.
