### ISSUE TITLE
https tweek for developing in cloud9 IDE

### ISSUE THREAD

**Issue by Uili-Simteau** [objectivehtml/FlipClock#297]
Hi there,

I'm enjoying using your library thanks.

I've found, when playing with the examples in the Cloud9 IDE, I've had to change all the insecure requests to http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js to https. 

I think this is because the preview instantiates with https, and finds a conflict when it previews.

Maybe a mention in the ReadMe? or modifying all the ajax calls to https? No biggie.
Cheers,

Uili

**Comment by objectivehtml** [comment]
Closing this as the new version doesn't have dependencies and the examples don't load jQuery.
