### ISSUE TITLE
Two digits in one flip

### ISSUE THREAD

**Issue by jmanses** [objectivehtml/FlipClock#300]
I'm creating a new face but I don't know how to put two digits into one flip (default is one digit one flip).
Similar to [this](https://image.freepik.com/free-psd/flip-clock_29-20000218.jpg)
Glad if anyone can help by letting me know which function/method should I work on.

I will share the code after I have successfully done the creation.

**Comment by objectivehtml** [comment]
Just addressing old posts. This is must more possible in the new v1 draft currently on the js-es6 branch. Closing this issue, but if anyone else still has this on the new version feel free to open a new one.
