### ISSUE TITLE
Multiple instances not working

### ISSUE THREAD

**Issue by MarcMueltin** [objectivehtml/FlipClock#310]
Hi there, 

I don't get multiple instances of Flipclock to work by just copying the HTML code with the ".countdown" class.
As in the base.html example, there is also a CSS class used, I was expecting that I can copy that div (in your example of base.html it is `<div class="clock" style="margin:2em;"></div>`) and all instances of that div would have the same behaviour. 
But it turns out that only the last FlipClock is working.

Here is my JS code:
--- JS Code ---
// Flipclock
var clock;
clock = new FlipClock($('.countdown'), {
    clockFace: 'DailyCounter',
    autoStart: false,
    callbacks: {
        stop: function() {
            $('.message').html('The limited offer EXPIRED!')
        }
    }
});

// Get the amount of seconds until limited offer ends and now. Needs to be passed on to setTime()
var startDate = new Date();
var endDate   = new Date('2017-03-07T11:00:00.000Z');
var seconds = (endDate.getTime() - startDate.getTime()) / 1000;

clock.setTime(seconds);
clock.setCountdown(true);
clock.start();
--- JS Code ---

I use two div containers, each with a class ".countdown". But does not work, see screenshot: 
<img width="687" alt="bildschirmfoto 2017-03-03 um 15 02 45" src="https://cloud.githubusercontent.com/assets/4791110/23541471/814364da-0022-11e7-87b8-a99079f31e83.png">

So do I have to copy the JS code for every instance and instead use CSS ids instead of classes to address the specific div container?

**Comment by clem91** [comment]
Regarding the architecture of this library, your proposition is the correct one. You have to instantiate a JS object for each div you want to animate

**Comment by objectivehtml** [comment]
Closing out old threads. This is correct, each instance of the clock must be instantiated with an element. The new version doesn't even use jQuery anymore.
