### ISSUE TITLE
Custom increment 

### ISSUE THREAD

**Issue by a-zhunusbekov** [objectivehtml/FlipClock#311]
How to increment `"clockFace: 'Counter'"` to ie. +600, not +1 every 1 hour? @objectivehtml Could you help me in that? 
Just writing `clock.increment(600);` doesn't works.

Here is my sample code
```
var clock = $('#cashback-counter').FlipClock(100000,{
	clockFace: 'Counter',
});
setTimeout(function() {
	setInterval(function() {
	.increment(600);
	}, 1000);
});
```

**Comment by objectivehtml** [comment]
This has been addressed in the new upcoming v1 currently on the js-es6 branch. You can also have an independent animation rate from the interval rate. This is no longer hardcoded to 1000ms.
