### ISSUE TITLE
Any chance of getting rid of JQuery?

### ISSUE THREAD

**Issue by felipenmoura** [objectivehtml/FlipClock#312]
Hi.
This project is awesome. I wanted to use it in a couple pages of mine, but they don't use JQuery.
This means I will have to load JQuery just for the FlipClock, in the page.

Is there any plans for stop using JQuery, or offering support for vanillaJS, anytime soon?

Again, awesome job :)

**Comment by objectivehtml** [comment]
Following up on old posts. jQuery and all dependencies have been ditched in the v1 draft currently on the js-es6 branch. 100% pure vanilla JS now, and written entirely in es6.
