### ISSUE TITLE
FlipClock Console Log

### ISSUE THREAD

**Issue by ahmad2smile** [objectivehtml/FlipClock#318]
I'm using FlipClock in angular 2 as a clock. How do I stop clock from console.log() current time out. The Source Line on log in the console is (unknown).

**Comment by fg123** [comment]
If you're using the minified version, Ctrl-F for `(a=this.getDateObject()),console.log(a)` and remove the `,console.log(a)` part. If you're using the full source, just remove all calls to `console.log` (I think the one in the source is `console.log(date)`. Granted, these should probably be removed in the release libraries...

**Comment by ahmad2smile** [comment]
Yep! already did that... I was trying not to edit the source code... ty anyways

**Comment by JamoCA** [comment]
I wouldn't mind seeing the incremented date/time in the console IF an debug option was set in order to output it and the default setting was `false` (ie, no output).

**Comment by objectivehtml** [comment]
No longer an issue in the new js-es6 branch.
