### ISSUE TITLE
As a hosted plugin

### ISSUE THREAD

**Issue by dinnexus** [objectivehtml/FlipClock#319]
Is it possible to make it available as a hosted plugin? Using Google Apps Script for Web Apps and there is no options to use the plugin without referencing to it like an external hosted plugin, like this when you need to import jQuery external to use it:
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

**Comment by objectivehtml** [comment]
This should be fixed in the new js-es6 branch. Closing this old thread.
