### ISSUE TITLE
AM/PM not working on 12hour clockface

### ISSUE THREAD

**Issue by jaaplaya** [objectivehtml/FlipClock#321]
I have this simple clock setup:

```
<html>
	<head>
		<link rel="stylesheet" href="/dashboards/assets/css/flipclock.css">

		<script src="/dashboards/assets/lib/jquery/dist/jquery.min.js"></script>

		<script src="/dashboards/assets/js/flipclock.js"></script>	
<style>
.clock{
zoom: 0.75;
-moz-transform: scale(0.75)
}
</style>	
	</head>
	<body>
		<div class="clock" style="margin:0em;"></div>
		<script type="text/javascript">
			var clock;
			
			$(document).ready(function() {
				var date = new Date('2017-05-27 14:27:33');
				
				clock = $('.clock').FlipClock(date, {
					clockFace: 'TwelveHourClock',
					showSeconds: false
				});
			
			});
		</script>
	</body>
</html>
```

It seems to be working properly in that it shows 01:27 on the clock face and works appropriately however it says that is 01:27 AM instead of PM.   I am generating the time in for another timezone and putting it into the date var.

It appears that when the AM/PM stuff is called it gets sent just the 12hour value (01) and not the 24hr value or something similar. 

The javascript console is logging the correct time although it says its PST when its really an EST time thats set (my local TZ is PST but the time i'm passing is an EST time)

> Sat May 27 2017 13:30:47 GMT-0700 (Pacific Daylight Time)

I tried mucking with the js code a bunch to try and get it fixed but i am not that good of a js developer to fix it, any help would be appreciated.

**Comment by ImbackAssholes** [comment]
Where did they go? How can they just abandon the most epic clock to ever be made ?

**Comment by objectivehtml** [comment]
Library no longer abandoned. Long time coming, but I finally rewrote this clock for ES6, webpack, npm, all the latest JS stuff. Checkout the js-es6 branch and this should all be fixed. Closing this thread. Re-open if its still an issue on the new version.

**Comment by jaaplaya** [comment]
Thanks!  new version does indeed fix it.  Thanks again!
