### ISSUE TITLE
Count down should go in negative value after zero

### ISSUE THREAD

**Issue by sanjaychavan1991** [objectivehtml/FlipClock#324]
I need to show the negative value for count down, after it's value goes bellow zero. Please suggest some thing to achieve this.
Thanks in advance.

**Comment by Darkmift** [comment]
Maybe a while loop with a timeinterval as required?

**Comment by sanjaychavan1991** [comment]
@Darkmift Can you please explain me little bit more I'm using flipclock for first time. I just want to show negative values after my count down goes bellow zero value

**Comment by objectivehtml** [comment]
This has been fixed in the new v1 draft release currently on the js-es6 branch. Now supports non numeric and alpha characters.
