### ISSUE TITLE
Firefox Counter Problem

### ISSUE THREAD

**Issue by enessefak** [objectivehtml/FlipClock#326]
![untitled](https://user-images.githubusercontent.com/10434186/28113280-a0b80f34-6704-11e7-9557-20691c2e1370.png)
![untitled](https://user-images.githubusercontent.com/10434186/28113837-d7c4503a-6706-11e7-8895-f4ecc8f77e19.png)

**Comment by killerbees19** [comment]
I had the same problem, but only when the clock (or it's parent objects) are displayed with **center alignment**. It didn't matter if you position it via plain HTML or via CSS.

You can see my (Javascript) workaround here: https://www.esports.happytec.at/

```javascript
function flipclock_center(id, container)
{
       callback = function()
       {
               $('#' + container).css('position', 'relative');
               $('#' + container).css('left', Math.round(($('#' + container).parent().width() - $('#' + id).width()) / 2) + 'px');
       };

       $(document).ready(callback);
       $(window).on('resize', callback);
}
```

```html
<div>
	<div class="flip-clock-container" id="countdown_desktop_container">
		<div id="countdown_desktop"><div align="center">Static text...</div></div>
		<div class="flip-clock-overlay"><a href="./"><img alt="" src="pixel.gif" border="0" style="width: 100%; height: 100%;"></a></div>
	</div>
<div>

<script type="text/javascript">

	$(document).ready(function()
	{
		flipclock_countdown('countdown_desktop', 1616685, '&ndash;');
		flipclock_center('countdown_desktop', 'countdown_desktop_container');
	});

</script>

```

Modified files: [functions_flipclock.js](https://www.happytec.at/js/functions_flipclock.js) & [flipclock_small.css](https://www.happytec.at/style/css/flipclock_small.css)

**Comment by killerbees19** [comment]
I had the same problem, but only when the clock (or it's parent objects) are displayed with **center alignment** and **width is uneven**. You can see my (Javascript based) workaround here: [Live Demo (two flipclocks)](https://www.esports.happytec.at/)

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<script src="https://www.happytec.at/js/jquery-2.1.1.js" type="text/javascript"></script>
		<script src="https://www.happytec.at/js/flipclock.js" type="text/javascript"></script>
		<script src="https://www.happytec.at/js/functions_flipclock.js" type="text/javascript"></script>
		<link rel="stylesheet" media="all" href="https://www.happytec.at/style/css/flipclock_small.css" type="text/css">
		<title>Example</title>
	</head>
	<body>
		<div style="padding: 15px;">
			<div class="flip-clock-container" id="countdown_container">
				<div id="countdown">
					<div align="center">
						Static text...
					</div>
				</div>
				<div class="flip-clock-overlay">
					<a href="http://example.com/">
						<img alt="" src="https://www.happytec.at/images/pixel_transparent.gif" border="0" style="width: 100%; height: 100%;">
					</a>
				</div>
			</div>
		<div>

		<script type="text/javascript">

			$(document).ready(function()
			{
				flipclock_countdown('countdown', 1616685, '&ndash;');
				flipclock_center('countdown', 'countdown_container'); // <-- RELEVANT LINE!
			});

		</script>
	</body>
</html>
```

Modified files: [functions_flipclock.js](https://www.happytec.at/js/functions_flipclock.js) & [flipclock_small.css](https://www.happytec.at/style/css/flipclock_small.css)

**Comment by objectivehtml** [comment]
This shouldn't be an issue in the new version closing this old thread as the library as been rewritten. Open a new issue if anyone is still having issues on the new js-es6 branch, which is the v1 draft release.
