### ISSUE TITLE
what's the best way to update the countdown date

### ISSUE THREAD

**Issue by Olga--Smirnova** [objectivehtml/FlipClock#327]
I have a list of events and need to update the countdown on event click. What's the best way to do it? Is there a way to do this without re-Instantiating of a clock?

Regards,
Olga

**Comment by objectivehtml** [comment]
Answering old posts for others that may find them.... In the new v1 draft release, you would simple update the clock's value property and it will re-render the clock. `const clock = new FlipClock(el, 0); clock.value = 10;`
