### ISSUE TITLE
 trigger an action at a specific time

### ISSUE THREAD

**Issue by killerbong** [objectivehtml/FlipClock#333]
Hello,
I set up an countdown, and I would like to play an mp3 5min from the end. Is it possible ?
Thank's

**Comment by objectivehtml** [comment]
Old post, but assigning this to myself. This is a good idea for the v1 feature. There are a few ways to do it, but to make it easier in the library would be nice. There is currently a `stopAt` property that accepts any value or a callback function and will stop the clock at any moment.
