### ISSUE TITLE
Trying to start timer when countdown already at 0

### ISSUE THREAD

**Issue by menadio** [objectivehtml/FlipClock#334]
I'm attempting to display a count down clock for an event in my Laravel 5.4 application. I getting the event date dynamically and using it inside the FlipClock instance and though the countdown clock is displayed, it's just displaying zero. From developer tools i can see the message `Trying to start timer when countdown already at 0`

![countdown](https://user-images.githubusercontent.com/11036247/31056003-4593a7c2-a6c3-11e7-9560-24216d246f6d.PNG)

This is what my code looks like
```
<script>
    var eventDate = "{{$nextEvent->start}}";

    //console.log(eventDate);

    var clock = $('.clock').FlipClock(eventDate, {
        clockFace: 'DailyCounter',
        countdown: true,
        autoStart: true,
        //showSeconds: false
    });
</script>
```
console.log(eventDate) displays this `2018-08-25 00:00:00`

Almost losing my hair here especially since i'm no javascript expert. Just a basic user still learning

**Comment by pjotrsavitski** [comment]
Your issue is with the date just being a string, not an object See [this one](https://jsfiddle.net/m8v9z4LL/) for a working example.

The API docs does mention [FlipClock.Time](http://flipclockjs.com/api#time)

**Comment by objectivehtml** [comment]
In the new v1 draft, this syntax has changed and would be `new FlipClock(el, new Date('some date goes here'), {face: 'DayCounter'})`. Closing this issue. Reopen a new one for the new version if you are still having issues. Docs will be updated shortly for the new version.
