### ISSUE TITLE
FlipClock resets timer after refresh

### ISSUE THREAD

**Issue by NikolaGrujicic** [objectivehtml/FlipClock#335]
Could someone please help me,i found an outdated answer i need a solution to this problem for the latest version of FlipClock.js

**Comment by CoryT87** [comment]
I'm in the same boat as you! I really need to get this working. It sucks that it does that because it's the place holder page for my portfolio that I'm working on.

**Comment by NikolaGrujicic** [comment]
hahahah i am making it for mi first published web site hahahaha,i foud a solution i will send it to you tomorow when i wake up👍🏻😄

**Comment by NikolaGrujicic** [comment]
here you go the solution,you just need to add the js extension on the javascript files so that it works :D


On Oct 23, 2017, at 02:07 PM, Cory <notifications@github.com> wrote:



I'm in the same boat as you! I really need to get this working. It sucks that it does that because it's the place holder page for my portfolio that I'm working on.

**Comment by objectivehtml** [comment]
This is outside the scope of the library. If you want to maintain the state after refresh or whatever, you need to use local storage and handling the saving manually.
