### ISSUE TITLE
why not clearInterval the Timers？

### ISSUE THREAD

**Issue by tnicer** [objectivehtml/FlipClock#336]
me defined one the flipclock:
var timer = $('#id').FlipClock(second, {
			clockFace: 'MinuteCounter',
			countdown: true,
		})

why not clearInterval(timer)  ???
big god help me!!  thanks!!

**Comment by objectivehtml** [comment]
Just closing old issues. New version of the library uses requestAnimationFrame, not intervals. `clock.stop()` will stop the timer.
