### ISSUE TITLE
Issues with Hour countdown on same day

### ISSUE THREAD

**Issue by chrisgwynne** [objectivehtml/FlipClock#340]
All I get is 00:00:00

<script type="text/javascript">
			var clock;
			
			$(document).ready(function() {
				// Set dates.
				var futureDate  = new Date("November 17, 2017 00:00 PM GMT");
				var currentDate = new Date();

				// Calculate the difference in seconds between the future and current date
				var diff = futureDate.getTime() / 1000 - currentDate.getTime() / 1000;

				// Calculate day difference and apply class to .clock for extra digit styling.
				function dayDiff(first, second) {
					return (second-first)/(1000*60*60*24);
				}

				if (dayDiff(currentDate, futureDate) < 100) {
					$('.clock').addClass('twoDayDigits');
				} else {
					$('.clock').addClass('threeDayDigits');
				}

				if(diff < 0) {
					diff = 0;
				}

				// Instantiate a coutdown FlipClock
				clock = $('.clock').FlipClock(diff, {
					clockFace: 'HourlyCounter',
					countdown: true
				});
			});
		</script>

Any help?

**Comment by objectivehtml** [comment]
Closing this old issue.
