### ISSUE TITLE
FlipClock not sync with initial time.

### ISSUE THREAD

**Issue by yoko83** [objectivehtml/FlipClock#341]
I have a issue, i set initial time:

```
var date = new Date('<?=date("Y-m-d h:i:s a");?>');
clock = $('.clock').FlipClock(date, {
clockFace: 'TwentyFourHourClock'
});
```

Ok, but if i change my windows time, the clock change too.
I want sync with server time, help me, pls, tks

**Comment by objectivehtml** [comment]
Just for reference, you need to use timezones for this. The new js-es6 branch makes working with Date objects much easier. Open a new issue with new upcoming v1 if this is still an issue.
