### ISSUE TITLE
UI clock not show start with 60 seconds

### ISSUE THREAD

**Issue by bobolat** [objectivehtml/FlipClock#342]
i setup everything to make the daily counter just for 60 second, the problem is the ui clock show 00 instead of 60. it is posibble to show ui clock start with 60 instead of 00, 59, 58 etc

**Comment by objectivehtml** [comment]
Going back through old threads... Currently all the clock faces intentionally omit 60. This would require extending the clock faces to provide a seconds counter that didn't modulate the seconds at 60. 60 seconds is when it rolls over 1 minute, so FlipClock just ignore 60 in all the clock faces.
