### ISSUE TITLE
Is anybody maintaining this repo? So many pull requests!

### ISSUE THREAD

**Issue by mattez** [objectivehtml/FlipClock#344]
Hi guys? Is anybody maintaining this repo?

- So many pull requests here!
- Not compiled with last source - missing localizations etc
- Last tagged version is OLD

Some fork which is better maintained?

**Comment by szykov** [comment]
Check mine, at least you can compile it. Hungarian language pull request broke the build and seems nobody cares. :\

**Comment by objectivehtml** [comment]
Just circling back here. Been a long time since I was able to properly spend time on the repo. All new js-es6 branch takes care of much of the pull request issues. At the very least, paves the way with unit tests and things for the community to take forward.
