### ISSUE TITLE
multiple countdown

### ISSUE THREAD

**Issue by gat0s** [objectivehtml/FlipClock#345]
Hi!

What I want to do here is two clocks, one DD:HH and the other MM:SS, I then want to stack the divs when needed. ie

DD:HH:MM:SS
-or-
DD:HH
MM:SS

However, I can even get two simple countdowns to work.Can someone tell me what I am doing wrong, please? .... Please!!

Thanks!

`
<html>
	<head>
		<link rel="stylesheet" href="../compiled/flipclock.css">

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

		<script src="../compiled/flipclock.js"></script>		
	</head>
	<body>

	<div class="clock-1" data-countdown="2018/07/15 17:12:20" style="margin:2em;"></div>
	
	<div class="clock-2" data-countdown="2018/07/15 17:12:20" style="margin:2em;"></div>
	
	<div class="message"></div>

	<script type="text/javascript">
		var clocks = [];
		
		$(document).ready(function() {
			
			clocks.push($('.clock-1').FlipClock({
		        clockFace: 'DailyCounter'
		        countdown: true
		    }));
			clocks.push($('.clock-2').FlipClock({
		        clockFace: 'DailyCounter'
		        countdown: true
		    }));
		});
	</script>
	
	</body>
</html>
`

**Comment by objectivehtml** [comment]
This is an old thread, but this should be much easier in the new branch js-es6. The library has been rewritten and this should be easier. If anyone sees this and wants this, try the latest version.
