### ISSUE TITLE
Firefox glitch while not moving cursor

### ISSUE THREAD

**Issue by shanpee** [objectivehtml/FlipClock#347]
Here is an example
![ice_video_20180215-112008](https://user-images.githubusercontent.com/9085149/36252168-f4f24692-1243-11e8-889e-d5b163253cc2.gif)

Win7
Firefox 58.0.2 (64 bit)

**Comment by Cilyan** [comment]
Same here, Firefox 58.0.2, Linux 64 bits.

**Comment by objectivehtml** [comment]
This should be fixed in the new js-es6 branch, which is the v1 draft.
