### ISSUE TITLE
NPM contains outdated, seemingly heavily deprecated version

### ISSUE THREAD

**Issue by TomsOzols** [objectivehtml/FlipClock#351]
Hi guys!

Project depending solely on NPM here.
Would like to be able to use the event functionality, but it seems impossible with the version 0.7.8 which is currently the latest available version in NPM.

Any plans to release the newest 0.8.0?
A bit salty since it took a while to realize the inconsistency in versions and documentation.

**Comment by effel** [comment]
Yes, my boyfriend have same problem, he don't want to invite me on date, because of sadness.

**Comment by objectivehtml** [comment]
The newest v1 draft has fixed this. Library will be available with NPM and work with Webpack and all the latest build tools. It's currently in the js-es6 branch.
