### ISSUE TITLE
Show and Hide seconds Dynamically

### ISSUE THREAD

**Issue by regor2** [objectivehtml/FlipClock#353]
I have been trying all afternoon to show and hide the seconds using the various API functions. Do I have to 'stop' the clock `clock.stop();` , set a parameter and then start it with  `clock.start();` ? `clock.loadClockFace('clock', options)` 
This is super exasperating; or do I have to dynamically delete the object and recreate it in the options?

**Comment by objectivehtml** [comment]
This is completely possible in the new js-es6 branch, which is the official v1 draft. The new version has render functions and can be re-rendered after a value or anything changes.

`
const clock = new FlipClock(el, new Date, {face: 'MinuteCounter'});
clock.face.showSeconds = false;
clock.render();
`
