### ISSUE TITLE
could it customize the size？

### ISSUE THREAD

**Issue by aqnaruto** [objectivehtml/FlipClock#355]
i mean ,this wigdet do'nt suit my page well ,
could it automatically suit the father div? or must i modify the css's each part manually

**Comment by scooter12** [comment]
same!

**Comment by sreekanthsnair** [comment]
This is the best available clock :+1:  , the only feature it doesn't have is sizing but its the most important feature to have. Please add the support for sizing

**Comment by zangaibaby** [comment]
@aqnaruto 

![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)
![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)![default](https://user-images.githubusercontent.com/39050423/41221132-de65bb9a-6d95-11e8-9e89-fac56ba2dc52.png)

**Comment by objectivehtml** [comment]
This should be much more responsive in customizable css in the new js-es6 branch. This is the new v1 draft, and completely rewritten for modern use.
