### ISSUE TITLE
a large number of Shadows

### ISSUE THREAD

**Issue by 1394230111** [objectivehtml/FlipClock#358]
When I drag and move the flipclock, it produce a large number of Shadows.
Dose anyone have this problem?

![default](https://user-images.githubusercontent.com/5087845/38121440-bdc5dfa0-3401-11e8-9adb-419612a70bd5.png)

**Comment by objectivehtml** [comment]
Sorry for the late reply. I wonder if this is still an issue on the latest version of the library, which has been completely rewritten. If you still use FlipClock and want to try the new version, it was completely rewritten for ES6 and all the latest JS features. Checkout the js-es6 branch if you ever need to update you app. I will leave this thread open and see if I can whip up a drag/drop example some time for the new version.

**Comment by 1394230111** [comment]
Roger. That's great

**Comment by brianespinosa** [comment]
Going to go ahead and close this out since the new version should have definitely resolved some of that weirdness.

If I ever get some free time to throw at it, I also want to make some other clock faces. Maybe some more minimal options.
