### ISSUE TITLE
FlipClock is not a function

### ISSUE THREAD

**Issue by JorisDek** [objectivehtml/FlipClock#370]
Hi,

I got this error. I tried a lot of different ways of implementing it in my js.

I use NPM to install the package.

In my js file I got:

`const $ = require('jquery');
window.jQuery = $;
require('flipclock');

$(document).ready(function() {
  var clock = $('.clock').FlipClock();
});`

jQuery is working. I know this because i use Foundation framework and Slick carousell, but it still says: FlipClock is not a function.

Any ideas?

**Comment by wally666** [comment]
Latest package version does not work. Downgrade to i.e. 0.8.0.

**Comment by objectivehtml** [comment]
I would install the new js-es6 branch and use that with require/import's. I'm going to make some time coming up to finish the new build and make sure everything works well with npm by default. The new branch doesn't use jQuery at all, and in fact has no dependencies.
