### ISSUE TITLE
how to change flip clock label title use data attribute?

### ISSUE THREAD

**Issue by KantaPaul** [objectivehtml/FlipClock#373]
I don't change or update flip clock label title? But i change this use data attribute and also change clock label position top to bottom

**Comment by objectivehtml** [comment]
Not possible without written that code yourself. in the new js-es6 branch, the instantiation is explicit so you could easily incorporation these data-attributes yourself. I am not sure if the library will ever support these first hand. I think a better approach is a wrapper component to pass the attributes to the instantiation.
