### ISSUE TITLE
weeklycounter.js is not on the compiled flipclock.js

### ISSUE THREAD

**Issue by franciscomorenobd1** [objectivehtml/FlipClock#374]
Hi!

I see the commit for the weekly face counter here: https://github.com/objectivehtml/FlipClock/blob/ae18a3c0cb563e10dd79963238f357e1ce95a887/src/flipclock/js/faces/weeklycounter.js

Also the getWeekCounter is missing on the flipclock.js check here:
https://github.com/objectivehtml/FlipClock/blob/ae18a3c0cb563e10dd79963238f357e1ce95a887/src/flipclock/js/libs/time.js

But the weekly counter face is not on the compiled version of the flipclock, check here: 
https://github.com/objectivehtml/FlipClock/blob/master/compiled/flipclock.js

This can be fixed? With that we can use that clock face without modify our website code.

Regards.

**Comment by objectivehtml** [comment]
There is a new branch `js-es6`. The library was rewritten and this should be fixed.
