### ISSUE TITLE
Convert floats to inline-block

### ISSUE THREAD

**Issue by ajmas** [objectivehtml/FlipClock#379]
Playing around with the CSS I notice part of the issues of centering is due to the use of 'float'. It would probably be better to use inline-blocks instead:

```

.flip-clock-wrapper ul {
    float: none;
    display: inline-block;
}

.flip-clock-divider {
    float: none;
    display: inline-block;   
}

.flip-clock-wrapper {
   transform: scale(1.0);
   white-space: nowrap;
}
```

This then makes scaling that much simpler, since it responds nicely to:

```
transform: scale(0.3);
```

Also, it may be useful to a solution to selecting the font-size to be relative to the size of the parent div container?

**Comment by objectivehtml** [comment]
This is fixed in the `js-es6` branch. It's going to become the `master` branch very soon. The docs are finished and are in the repo if you want to check it out. It has true scaling, no floats etc.
