### ISSUE TITLE
Uncaught TypeError: clock.getFaceValue is not a function

### ISSUE THREAD

**Issue by atishagrawal** [objectivehtml/FlipClock#380]
I am trying to retrieve the current value using this function

```
var clock = $('.quota-clock').FlipClock(2000, {
        clockFace: 'Counter',
        countdown: true,
    });
console.log(clock.getFaceValue());
````
and I am getting this error:
`Uncaught TypeError: clock.getFaceValue is not a function`

Please tell me how to get the current value.

**Comment by objectivehtml** [comment]
This is the old version of FlipClock that hadn't been updated in a long time. `getValue()` might work. Or `getFace().getValue()`, I can't remember.

However, on `js-es6` branch is going to become master in the next couple of days and is a complete rewrite. The docs on in the repo on the new branch. In the upcoming v1, you would get the clock value just by doing `console.log(clock.value)`.

**Comment by lqzhgood** [comment]
`setTime` `getTime` in `Base.js, version 1.1a` not es6 version

should update docs or push Es6 version to master branch

**Comment by Dror-Bar** [comment]
@lqzhgood 
So, what are the new alternatives?
