### ISSUE TITLE
inherit * .15

### ISSUE THREAD

**Issue by bonesoul** [objectivehtml/FlipClock#381]
`animation-delay: calc(inherit * .15);`

this line prevents css minificators to work.

```
    Warning: Parse error on line 1:
    inherit * .15
    ^
    Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX' Use --force to continue.
```

any fixes?

**Comment by objectivehtml** [comment]
Thanks for this. In the latest version I have this fixed and just hardcoded 500ms (for now). I'll probably just make this value a sass variable or something. Look at the js-es6 branch. It will be the master branch very shortly. The docs are mostly finished and are in the repo.
