### ISSUE TITLE
When using as counter with starting value

### ISSUE THREAD

**Issue by TheWhykiki** [objectivehtml/FlipClock#382]
When using the Flipclock with the latest CSS from the download area, the counter starts with a strange initial value.  If I start with the value 240, the counter counts up one time from 139.,...

As I tested out, this behavior is only appearing with the new CSS, when using the CSS from 0.7.8 the counter starts at initial value.

**Comment by objectivehtml** [comment]
This is fixed in the newest version. Look at the js-es6 branch or install with NPM. The docs are in the repo. I should have the website updated in the next couple of days with the new docs, and this will be the master branch and be v1.0.0.
