### ISSUE TITLE
FlipClock not rendenring

### ISSUE THREAD

**Issue by balaji-ramya** [objectivehtml/FlipClock#383]
I am using js-es6 branch with aurelia.
import FlipClock from 'flipclock';
export class View{
attached(){
const el = document.querySelector('.clock');

    const clock = new FlipClock(el,new Date(), {
      face: 'HourCounter'
    });
}
}

html:

`<div class="clock"></div>`

It displays blank page. Am i missing any configs?

**Comment by objectivehtml** [comment]
This is a probably something I need to address in the build. Try this for now until I get a chance to fix this. Importing the root should be an alias for this... `import FlipClock from `flipclock/src/Components/FlipClock`

**Comment by balaji-ramya** [comment]
I tried this.  it does not render the clock.

**Comment by objectivehtml** [comment]
What build tool are you using?

**Comment by balaji-ramya** [comment]
no worries. I got it working.

**Comment by objectivehtml** [comment]
Just curious, can you post what you were doing wrong in case someone else searches and has the same issue?

**Comment by ayubUOL** [comment]
@balaji-ramya  Can you please share what changes did you made to fix the CSS for flipclock ? In my case, clock is working but css is not applying to clock.
