### ISSUE TITLE
clockFace isn't working

### ISSUE THREAD

**Issue by duongle-kdnd** [objectivehtml/FlipClock#385]
let clock = new FlipClock($('.countdown').get(0), 3600  * 24 * 3, {
     clockFace: 'DailyCounter',
    countdown: true,
});
I set like above, but it always display like the photo, although i change name of the clockFace. Please help me find the reason, i read all issue, but nobody is like me
![Screenshot_2019-06-17 okk](https://user-images.githubusercontent.com/51528630/59608868-7944d780-9140-11e9-9b84-cc61524983d1.png)

**Comment by tiesont** [comment]
`'.countdown'` is a class selector - is that valid for your markup? if you only have a single timer, it's probably better to use an id selector (something like `'#my-timer-id-here'`).
