### ISSUE TITLE
HourCounter resets with high hour count

### ISSUE THREAD

**Issue by Danielss89** [objectivehtml/FlipClock#386]
I want to add an hour counter to my website, starting from a date. Using the "counter-from-new-years" example, i changed it to use HourCounter face, instead of DayCounter. When the clock loads, it show the correct amount of hours "4000" and something, but at the first flip, it resets to 00:00:00 and starts counting up from this reset.
Is this a bug, or am i missing a setting?

**Comment by OrsoBruno96** [comment]
I confirm this issue. It doesn't work either with only a few hours (2).

## Package version
Package installed via `npm`. Version 0.10.8. I am using it in a React project

## Minimal example
```js
    const el = document.querySelector('#clock');
    const now = new Date();
    const end = new Date(now.getFullYear(), now.getMonth(),
      now.getDate(), now.getHours() + 2);
    const clock = new FlipClock(
      el, end, {
        face: 'HourCounter',
        countdown: true,
      });
```

The same identical code with the substitution `HourCounter` => `DayCounter` works well.

**Comment by Dror-Bar** [comment]
Wait, is there any solution to this?
You can hide seconds, but I don't think you can hide days...

**Comment by Dror-Bar** [comment]
For crying out loud, I spent a few hours digging in the code and I think I found the bug.
In flipclock.js line 3210:

Change this line:
`var now = !instance.timer.started ? new Date() : value;`

To this:
`var now = new Date();`

And the problem should be fixed.

**Comment by tbone849** [comment]
@Dror-Bar awesome! hopefully this doesn't break something else. so far, so good.

> I spent too many hours digging in the code and I think I found the bug.
> 
> In flipclock.js line 3210:
> 
> Change this line:
> `var now = !instance.timer.started ? new Date() : value;`
> 
> To this:
> `var now = new Date();`
> 
> And the problem should be fixed.

**Comment by Dror-Bar** [comment]
@tbone849 you may also be interested in [this](https://github.com/objectivehtml/FlipClock/pull/397/files) pull request. Look at some of his changes in dist/flipclock.js. He added more stuff, so it might be more robust than my solution.

**Comment by tbone849** [comment]
> @tbone849 you may also be interested in [this](https://github.com/objectivehtml/FlipClock/pull/397/files) pull request. Look at some of his changes in dist/flipclock.js. He added more stuff, so it might be more robust than my solution.

Interesting. I wonder if it really changes anything. The hour counter still seems to work perfectly per your change. I wonder if there is a circumstance where that wouldn't be the case. At any rate, it doesn't seem to affect my use case. I know this project is the last on the contributors minds with likely bigger fish to fry. I wish they would at least manage the simpler pull requests.

**Comment by 54keesh** [comment]
@Dror-Bar Thanks a lot buddy, I have been rubbing my head for hours in side the codebase to see whats wrong. Your fix did the trick
