### ISSUE TITLE
scaling FlipClock

### ISSUE THREAD

**Issue by jdittrich** [objectivehtml/FlipClock#54]
I want to use flipclock in place with spacial constraints, e.g. a sidebar. 

**Problem:** There is a css file, but It is difficult to customize the CSS, as a lot is coded in pixels. I always messed it up at some point. 
**Possible Solutions:** Is there an alternative stylesheet or some other means to scale the clock?

(It seems that the stylesheet is quite sophisticated for the reasons of the great appearance. It would not pose a problem not to have all the nice effects in a scaling version imho) 

PS.: What I tried was to change width and height of `.flip-clock-wrapper ul` and font-size in `.flip-clock-wrapper ul li a div div.inn`. It works mostly, but always messed up at the end, probably due to some side effects I was not able to control.

**Comment by ion99** [comment]
Thank you!

**Comment by acorreaf** [comment]
https://codepen.io/rikschennink/details/lyuaf
