### ISSUE TITLE
Add Yearly and Monthly Counter

### ISSUE THREAD

**Issue by hardikgosai** [objectivehtml/FlipClock#56]
I do have requirement of count up counter and i want to add Yearly and Monthly like Daily, Hourly.

Please provide solution ASAP. As this might be the enhancement to this plugin.

**Comment by Zetalia** [comment]
Hi, 

i am also looking for a way to add Years to the counter.
@EricSmekens do you have a workaround ready that i could use to display years?

**Comment by EricSmekens** [comment]
No, currently I don't have a workaround for this. Problem is that not every month/year is of the same duration. So you need to add a start-time or something like that. It is ofcourse possible, but I didn't had time to do it.
