### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by paulgessinger** [objectivehtml/FlipClock#74]
I'm currently using FlipClock on a project I am working on. I noticed Google Chrome running at ~50% on me 2011MBA, which makes the fans go at max rpm within a minute or so. I think this is due to the insane amount of animations that are (necessarily) performed. 

While I see that there is no way around this particular issue, however, it might be helpful if the clock stopped triggering animations when the tab becomes invisible. 
I think this might be achieved by using requestAnimationFrame to trigger the CSS animations, since that callback is only fired, when the respective tab is currently viewed. This could alleviate the problem. 

There is also document.addEventListener("visibilitychange"), so I think one could work around this from the outside by just stopping the clock an enabling it ones visibility is restored, however it might be more elegant to deal with this right inside the library.

**Comment by pynixwang** [comment]
1 instance 20% cpu

**Comment by pynixwang** [comment]
it not acceptable now.
