### ISSUE TITLE
Thousands separator 

### ISSUE THREAD

**Issue by fredw** [objectivehtml/FlipClock#91]
It would be interesting in face of the counter to have an option of thousand separator.
For very large numbers is hard to read them.

**Comment by coreyleedesigns** [comment]
+1 on this feature

**Comment by rjksn** [comment]
I'm just doing this now for a project—here looking at scaling—so this isn't final, or overly pretty. But, add this in a separate JS before you call it.

	(function($) {
			
		/**
		 * Counter Clock Face
		 *
		 * This class will generate a generice flip counter. The timer has been
		 * disabled. clock.increment() and clock.decrement() have been added.
		 *
		 * @param  object  The parent FlipClock.Factory object
		 * @param  object  An object of properties to override the default	
		 */
		 
		FlipClock.CashFace = FlipClock.Face.extend({
			
			/**
			 * Tells the counter clock face if it should auto-increment
			 */

			shouldAutoIncrement: false,

			/**
			 * Constructor
			 *
			 * @param  object  The parent FlipClock.Factory object
			 * @param  object  An object of properties to override the default	
			 */
			 
			constructor: function(factory, options) {

				if(typeof options != "object") {
					options = {};
				}

				factory.autoStart = options.autoStart ? true : false;

				if(options.autoStart) {
					this.shouldAutoIncrement = true;
				}

				factory.increment = function() {
					factory.countdown = false;
					factory.setTime(factory.getTime().getTimeSeconds() + 1);
				};

				factory.decrement = function() {
					factory.countdown = true;
					var time = factory.getTime().getTimeSeconds();
					if(time > 0) {
						factory.setTime(time - 1);
					}
				};

				factory.setValue = function(digits) {
					factory.setTime(digits);
				};

				factory.setCounter = function(digits) {
					factory.setTime(digits);
				};

				this.base(factory, options);
			},

			/**
			 * Build the clock face	
			 */
			 
			build: function() {
				var t        = this;
				var children = this.factory.$el.find('ul');
				var time 	 = this.factory.getTime().digitize([this.factory.getTime().time]);

				if(time.length > children.length) {
					$.each(time, function(i, digit) {
						var list = t.createList(digit);

						list.select(digit);
					});
				
				}

				$.each(this.lists, function(i, list) {
					list.play();
				});


				if ( time.length > 3 ) {
					this.createDivider();
					$(this.dividers[0]).insertBefore(this.lists[this.lists.length - 3].$el);

					if ( time.length > 6 ) {
						this.createDivider();
						$(this.dividers[1]).insertBefore(this.lists[this.lists.length - 6].$el);

						if ( time.length > 9 ) {
							this.createDivider();
							$(this.dividers[2]).insertBefore(this.lists[this.lists.length - 9].$el);

							if ( time.length > 12 ) {
								this.createDivider();
								$(this.dividers[3]).insertBefore(this.lists[this.lists.length - 12].$el);
							}
						}
					}
				}

				this.base();
			},

			createDivider: function(label, css, excludeDots) {
				if(typeof css == "boolean" || !css) {
					excludeDots = css;
					css = label;
				}

				var dots = [
					'<span class="'+this.factory.classes.dot+' comma">,</span>'
				].join('');

				if(excludeDots) {
					dots = '';	
				}

				label = this.factory.localize(label);

				var html = [
					'<span class="'+this.factory.classes.divider+' '+(css ? css : '').toLowerCase()+'">',
						'<span class="'+this.factory.classes.label+'">'+(label ? label : '')+'</span>',
						dots,
					'</span>'
				];	
				
				var $html = $(html.join(''));

				this.dividers.push($html);

				return $html;
			},
			
			/**
			 * Flip the clock face
			 */
			 
			flip: function(time, doNotAddPlayClass) {			
				if(this.shouldAutoIncrement) {
					this.autoIncrement();
				}

				if(!time) {		
					time = this.factory.getTime().digitize([this.factory.getTime().time]);
				}

				this.base(time, doNotAddPlayClass);
			},

			/**
			 * Reset the clock face
			 */

			reset: function() {
				this.factory.time = new FlipClock.Time(
					this.factory, 
					this.factory.original ? Math.round(this.factory.original) : 0
				);

				this.flip();
			}
		});
		
	}(jQuery));

CSS

	.flip-clock-wrapper .flip-clock-dot.comma {
		display: block;
		width: auto;
		height: auto;
		position: absolute;
		border-radius: 0;
		box-shadow: none; 
		background: transparent;
		bottom: -10px;
		font-size: 70px;
		margin-left: -5px;
	}

Call the Clock

	var clock = $('#drawvalue').FlipClock( 250000, {
		clockFace: 'Cash'
	});

**Comment by schester44** [comment]
@rjksn Thank you for this! I was able to modify some of the code to add styled commas and dollar signs. 
My problem is when we setValue() from say $10000.00 down to $100.00, it reads as $00100.00. Where in this code would I remove the digits that are no longer there? Also, have you found a way to make this work with cents? ex $100.50. It works but the commas are misplaced.

**Comment by rjksn** [comment]
I didn't need to for my use case, and thankfully I'm only counting up! I
believe it happened there as well going from say 1e5 to 1e6, I don't think
I bothered solving that, since I was counting donations I didn't break into
the tens of millions.

On Mon, Jun 13, 2016, 1:50 PM Steve Chester, <notifications@github.com>
wrote:

> @rjksn <https://github.com/rjksn> Thank you for this! I was able to
> modify some of the code to add styled commas and dollar signs.
> My problem is when we setValue() from say $10000.00 down to $100.00, it
> reads as $00100.00. Where in this code would I remove the digits that are
> no longer there? Also, have you found a way to make this work with cents?
> ex $100.50. It works but the commas are misplaced.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/objectivehtml/FlipClock/issues/91#issuecomment-225656825>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHSUSAGq6ClKS7MI_pHKom23fhz4Go4ks5qLZhOgaJpZM4BuYzj>
> .
>
-- 

Ryan Jackson | 613-797-1984 | ryan@rjackson.ca

**Comment by objectivehtml** [comment]
New version of this library can handle alpha characters. In fact anything with a toString() method can be digitized and set in the clock face. Closing this old issue, but will try to get an example of this for the new version.
