### ISSUE TITLE
Responsive FlipClockJs

### ISSUE THREAD

**Issue by ramidr** [objectivehtml/FlipClock#92]
Hi,

how do you do in your flipclockjs.com index page responsive clock? when I resizes the window or when I visits the web through a mobile device the clock resize correctly.

any ideas? thanks a lot!

**Comment by kamciok** [comment]
Here is how I've sorted it out. Maybe it's not perfect but it works for my Angular project. It SCSS code. There are some responsive Angular Material mixins included.

```
  .flip-clock-divider {
    @include respondto(xs) {
      &:nth-of-type(3) {
        .flip-clock-label{
          margin-left: -10px;
          top: 9em;
          left: -550px;
        }
        .flip-clock-dot.top,  .flip-clock-dot.bottom {
          display: none;
        }
      }
    }
    .flip-clock-label {
      @include respondto(gt-sm) {
        font-size: 1.2em;
      }
    }
  }
  @media screen and (max-width: 330px) {
    .flip-clock-wrapper {
      min-width: 300px;

      ul {
        width: 50px;
        height: 60px;
        line-height: 70px;
        margin-bottom: 30px;
        li {
          line-height: 60px;
          a {
            div div.inn {
              font-size: 40px;
            }
          }
        }
      }
    }
    .flip-clock-divider {
      height: 80px;
      &:nth-of-type(3) {
        .flip-clock-label{
          margin-left: -10px;
          top: 7em;
          left: -500px;
        }
        .flip-clock-dot.top,  .flip-clock-dot.bottom {
          display: none;
        }
      }
    }
    .flip-clock-dot.top {
      top: 20px;
    }
    .flip-clock-dot.bottom {
      bottom: 25px;
    }
  }
```

**Comment by DSergioD** [comment]
`<div class="row" id="countdown">
    <div class="col-sm-12 col-md-6 col-md-offset-3 overflow-hidden">
        <div class="clock" id="clock"></div>
        <div class="message"></div>
    </div>
</div>

 // Resize 
    function startResizing() {
        // resize Add
        resizeElement();
        window.addEventListener("resize", resizeElement);
    }
    function resizeElement() {
        var scaling;
        // wenn window height kleiner als doppelt so groß wie width:
        if (getActualHeight() < getActualWidth()) {
        } else {
            document.getElementById('countdown').style.width = getActualWidth();
            scaling = getActualWidth() / 670;
            if (scaling > 1) {
                scaling = 1;
            } else {
                scaling = getActualWidth() / 670;
            }
            //console.log(scaling);
            if (document.getElementById('clock')) {
                document.getElementById('clock').style.transform = 'scale(' + scaling + ')';
            }
        }
    }

    function getActualWidth() {
        var actualWidth = window.innerWidth ||
            document.documentElement.clientWidth ||
            document.body.clientWidth ||
            document.body.offsetWidth;
        return actualWidth;
    }

    function getActualHeight() {
        var actualHeight = window.innerHeight ||
            document.documentElement.clientHeight ||
            document.body.clientHeight ||
            document.body.offsetHeight;
        return actualHeight;
    }
    document.addEventListener('DOMContentLoaded', startResizing, false);
    document.addEventListener('load', function(){ startResizing() } );

Works like a charm.`
